$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
ignorePaths:
  - .git
  - .vercel
  - .next
  - .astro
  - bun.lockb
  - ./branch_out
  - .changeset
  - drizzle
  - '**/*.svg'
words:
  - Aaiun
  - Ababa
  - abcdefghijklmopqrstuvwxyz
  - acst
  - actionables
  - Adak
  - Addis
  - aest
  - akst
  - aliqua
  - amet
  - Amet
  - Anadyr
  - Anson
  - apitoken
  - Aqtau
  - Aqtobe
  - Araguaina
  - Asmera
  - astro
  - astrojs
  - astrolib
  - Atikokan
  - Atka
  - Atyrau
  - autodocs
  - automations
  - Automations
  - autoplay
  - autoset
  - AVATARBOX
  - awst
  - backgroun
  - backgroundfill
  - Baja
  - Banderas
  - Barthelemy
  - basemaps
  - Bator
  - Beamer
  - behance
  - Bento
  - Binni
  - Blocke
  - Blockquotes
  - blueprintjs
  - boxshadow
  - branchname
  - Branco
  - bunx
  - burndown
  - burndowns
  - Busingen
  - bvaughn
  - Byrom
  - callees
  - camdynn
  - Camdynn
  - Catamarca
  - chartjs
  - Choibalsan
  - Chuuk
  - Ciudad
  - cjsx
  - classname
  - clsx
  - cmax
  - cmdk
  - cmin
  - codebl
  - codefence
  - codemark
  - codemirror
  - codepreview
  - codesandbox
  - codespace
  - codespaces
  - collab
  - Colm
  - colorwheel
  - colwidth
  - commitish
  - commitlint
  - commitlintrc
  - Comod
  - Comonent
  - compat
  - Concepting
  - connectingfrom
  - connectingto
  - connectionindicator
  - connectionline
  - consequat
  - Consolas
  - consts
  - Consulty
  - coverflow
  - cpath
  - Creston
  - crossorigin
  - ÇŞĞIİÖÜA
  - csvg
  - ctsx
  - Cuiaba
  - customkeymap
  - Dacca
  - Danmarkshavn
  - dashdraw
  - datetime
  - dbaeumer
  - decos
  - degit
  - deserunt
  - Designboise
  - Dili
  - directus
  - doctag
  - docummentation
  - dotenv
  - dotlottie
  - downlaods
  - dribbble
  - dropcursor
  - dropmenu
  - dsznajder
  - Duarte
  - duis
  - Dumont
  - duplicable
  - dwireframe
  - edgelabel
  - edgeupdater
  - Efate
  - Eirunepe
  - Elsakaan
  - Embla
  - encapsulte
  - Enderbury
  - enim
  - Ensenada
  - esbenp
  - eslintcache
  - Eucla
  - evenodd
  - exitable
  - explor
  - Explor
  - Extralight
  - Fakaofo
  - favorited
  - FAVORITED
  - Figtree
  - filesize
  - fkey
  - flipbehavior
  - floatingedges
  - focusable
  - fromnow
  - frontmatter
  - gantt
  - Gantt
  - gapcursor
  - Gapcursor
  - giest
  - Gitbook
  - Gloock
  - googleanalytics
  - gradia
  - grotesk
  - grouphover
  - haspopup
  - headlessui
  - hellsangels
  - heroicons
  - highlightjs
  - hightlights
  - hitbox
  - hljs
  - hookform
  - Hovd
  - Hoverable
  - Hubspot
  - HYWE
  - ianvs
  - Ideanote
  - iefix
  - Ifwg
  - indexeddb
  - Indexeddb
  - Inuvik
  - Issuefields
  - jiti
  - jscoverage
  - jspm
  - JTBD
  - Jujuy
  - Kanban
  - Kanton
  - keymap
  - Keymap
  - Khandyga
  - Kiritimati
  - Kitts
  - kohler
  - Kolkata
  - Kosrae
  - Kralendijk
  - Kuala
  - labil
  - laquo
  - Leveln
  - Lindeman
  - linecap
  - linejoin
  - Lnan
  - lockb
  - Logomark
  - Longyearbyen
  - lottiefiles
  - lowlight
  - Lowlight
  - lucide
  - lumkey
  - Lumpur
  - machine
  - Magadan
  - Mahe
  - Malyavko
  - Manaus
  - mapbox
  - marching
  - Marigot
  - Marino
  - matching
  - Mayen
  - measurables
  - Memoji
  - Menlo
  - MENUBOX
  - Metlakatla
  - microbundle
  - mikestead
  - Minh
  - minimise
  - Mintlify
  - mjsx
  - mollit
  - monokai
  - monorepoing
  - Moresby
  - mousewheel
  - mtsx
  - Murdo
  - neonctl
  - neondatabase
  - Nera
  - nesw
  - Neue
  - nextjs
  - Nipigon
  - nivo
  - nocheck
  - nodesselection
  - nodrag
  - noopener
  - nopan
  - noreferrer
  - Noronha
  - Norte
  - Noto
  - nowrap
  - nums
  - Nuuk
  - nuxt
  - nzst
  - odzdpcvclydcqawdagdt
  - officia
  - Ojinaga
  - ondark
  - onwarn
  - optimisations
  - orbitkit
  - Ornella
  - packagejson
  - pacocoursey
  - pageview
  - Pago
  - Pandang
  - Pangnirtung
  - pannable
  - passowrd
  - pathline
  - peduarte
  - Pendo
  - pids
  - Pinterest
  - pkce
  - plutio
  - Pohnpei
  - popperjs
  - Postgrest
  - posthog
  - posx
  - powerlines
  - Preconfigured
  - preconnect
  - prerender
  - Presstek
  - prodkt
  - prodkthero
  - progressbar
  - proptected
  - prosemirror
  - Prosemirror
  - Psnhw
  - Punta
  - Qostanay
  - quickstart
  - Qyzylorda
  - raquo
  - Ratelimit
  - reactflow
  - reparent
  - resizer
  - revolutionvodka
  - rgba
  - Rica
  - Rioja
  - Ritalic
  - Rivadavia
  - Roadmaps
  - rotatex
  - Rothera
  - rowspan
  - Sablon
  - sandpack
  - Santarem
  - Santo
  - scatterplot
  - Scoresbysund
  - scroller
  - Segoe
  - selectednode
  - selectionpane
  - seperator
  - servicemark
  - shadcn
  - Shiprock
  - signin
  - signup
  - slidek
  - sonner
  - Squircle
  - squoosh
  - srcdoc
  - Srednekolymsk
  - sslmode
  - Stabil
  - Starke
  - starterkit
  - starterkits
  - styledictionary
  - stylelint
  - stylelintcache
  - stylesheet
  - subgrid
  - subline
  - sublist
  - Sublist
  - supabase
  - superjson
  - SVGR
  - Swiper
  - Syowa
  - tada
  - tailwindcss
  - tamasfe
  - tanstack
  - textareas
  - textbg
  - textblock
  - Textblock
  - textnodes
  - textwrapper
  - Themeing
  - thollander
  - tiktok
  - timebox
  - timeboxed
  - TINYBIRD
  - tippyjs
  - tiptap
  - Tiptap
  - Tiraspol
  - todos
  - tokensstudent
  - tokentype
  - Tongatapu
  - topbar
  - tovuti
  - transitionall
  - transpiles
  - treeshake
  - trpc
  - truwhip
  - tsbuildinfo
  - tsconfigs
  - tseslint
  - tsup
  - tubro
  - Tuite
  - turborepo
  - typecheck
  - typeof
  - typesafe
  - Ujung
  - Ulaanbaatar
  - Ulan
  - ullamco
  - unfavorited
  - UNFAVORITED
  - unifiedjs
  - Uniforma
  - unkey
  - unstarted
  - Unstarted
  - uploadthing
  - upvoted
  - upvoters
  - upvotes
  - upvoting
  - Urville
  - Ushuaia
  - uuidv
  - Uzhgorod
  - vaul
  - Velho
  - Velit
  - vercel
  - Vevay
  - viewports
  - vuepress
  - waitlist
  - webp
  - wght
  - Winamac
  - wireframe
  - wireframes
  - WITA
  - wscript
  - xyflow
  - Yada
  - Yakutat
  - Yancowinna
  - yoav
  - zipball
  - zoomable
  - zoompane
  - ZUEP
  - zustand
  - zxcvbn
