$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
ignorePaths:
  - .git
  - .vercel
  - .next
  - .astro
  - bun.lockb
  - ./branch_out
  - .changeset
  - drizzle
  - '**/*.svg'
words:
  - acst
  - aest
  - akst
  - aliqua
  - amet
  - Amet
  - Anson
  - apitoken
  - astro
  - astrojs
  - autodocs
  - autoplay
  - awst
  - backgroun
  - backgroundfill
  - basemaps
  - Beamer
  - behance
  - Bento
  - Binni
  - boxshadow
  - branchname
  - bunx
  - bvaughn
  - Byrom
  - callees
  - camdynn
  - Camdynn
  - cjsx
  - classname
  - clsx
  - cmax
  - cmdk
  - cmin
  - codebl
  - codefence
  - codemirror
  - codepreview
  - codesandbox
  - codespace
  - codespaces
  - Colm
  - colorwheel
  - commitlint
  - commitlintrc
  - Comonent
  - compat
  - Concepting
  - connectingfrom
  - connectingto
  - connectionindicator
  - connectionline
  - consequat
  - Consolas
  - consts
  - Consulty
  - coverflow
  - cpath
  - crossorigin
  - csvg
  - ctsx
  - dashdraw
  - datetime
  - dbaeumer
  - degit
  - deserunt
  - Designboise
  - directus
  - docummentation
  - dotenv
  - dribbble
  - dropmenu
  - dsznajder
  - Duarte
  - duis
  - dwireframe
  - edgelabel
  - edgeupdater
  - Elsakaan
  - Embla
  - enim
  - esbenp
  - eslintcache
  - evenodd
  - explor
  - Explor
  - Extralight
  - Figtree
  - filesize
  - fkey
  - floatingedges
  - focusable
  - frontmatter
  - Gitbook
  - Gloock
  - googleanalytics
  - gradia
  - grotesk
  - grouphover
  - haspopup
  - headlessui
  - hellsangels
  - heroicons
  - highlightjs
  - hljs
  - hookform
  - Hoverable
  - HYWE
  - ianvs
  - Ideanote
  - Ifwg
  - jiti
  - jscoverage
  - jspm
  - Kanban
  - kohler
  - labil
  - Leveln
  - linecap
  - linejoin
  - Lnan
  - lockb
  - Logomark
  - lucide
  - Malyavko
  - mapbox
  - Memoji
  - Menlo
  - microbundle
  - mikestead
  - minimise
  - Mintlify
  - mjsx
  - mollit
  - monokai
  - monorepoing
  - mousewheel
  - mtsx
  - neonctl
  - neondatabase
  - nesw
  - Neue
  - nextjs
  - nocheck
  - nodesselection
  - nodrag
  - nopan
  - Noto
  - nowrap
  - nums
  - nuxt
  - nzst
  - odzdpcvclydcqawdagdt
  - officia
  - ondark
  - onwarn
  - optimisations
  - orbitkit
  - Ornella
  - packagejson
  - pacocoursey
  - pageview
  - pannable
  - peduarte
  - Pendo
  - pids
  - Pinterest
  - pkce
  - plutio
  - Postgrest
  - posthog
  - posx
  - powerlines
  - Preconfigured
  - preconnect
  - prerender
  - Presstek
  - prodkt
  - prodkthero
  - progressbar
  - proptected
  - Psnhw
  - quickstart
  - Ratelimit
  - reactflow
  - resizer
  - revolutionvodka
  - rgba
  - Ritalic
  - Roadmaps
  - rotatex
  - sandpack
  - scroller
  - Segoe
  - selectionpane
  - shadcn
  - signin
  - slidek
  - sonner
  - Squircle
  - squoosh
  - srcdoc
  - sslmode
  - Stabil
  - starterkit
  - starterkits
  - styledictionary
  - stylelint
  - stylelintcache
  - stylesheet
  - subgrid
  - subline
  - supabase
  - superjson
  - SVGR
  - Swiper
  - tada
  - tailwindcss
  - tamasfe
  - tanstack
  - textareas
  - textbg
  - textnodes
  - textwrapper
  - Themeing
  - thollander
  - tiktok
  - todos
  - tokensstudent
  - tokentype
  - topbar
  - tovuti
  - transitionall
  - transpiles
  - treeshake
  - trpc
  - truwhip
  - tsbuildinfo
  - tsconfigs
  - tseslint
  - tsup
  - Tuite
  - turborepo
  - typecheck
  - typeof
  - typesafe
  - ullamco
  - unifiedjs
  - Uniforma
  - unkey
  - uploadthing
  - upvoters
  - upvotes
  - upvoting
  - vaul
  - Velit
  - vercel
  - viewports
  - vuepress
  - waitlist
  - webp
  - wght
  - wireframe
  - wireframes
  - WITA
  - wscript
  - xyflow
  - Yada
  - yoav
  - measurables
  - MENUBOX
  - Hubspot
  - AVATARBOX
  - zoomable
  - zoompane
  - ZUEP
  - zustand
