/* eslint-disable @eslint-community/eslint-comments/disable-enable-pair */
/* eslint-disable @typescript-eslint/no-unsafe-assignment */
/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @typescript-eslint/no-unsafe-call */

import type { Config } from 'tailwindcss'

import aspectRatio from '@tailwindcss/aspect-ratio'
import containerQueries from '@tailwindcss/container-queries'
import forms from '@tailwindcss/forms'
import typography from '@tailwindcss/typography'
import animate from 'tailwindcss-animate'
import plugin from 'tailwindcss/plugin'
import { createPlugin } from 'windy-radix-palette'
import windyTypography from 'windy-radix-typography'

const colors = createPlugin()

export const prodktTailwindPreset: Config = {
  content: ['./src/**/*.{js,jsx,ts,tsx,mdx,astro}'],
  presets: [windyTypography],
  theme: {
    extend: {
      backgroundImage: {
        'radial-gradient-1':
          'radial-gradient(87.07% 87.07% at 52.38% 100%, var(--grayA1) 0%, var(--grayA6) 100%)',
        'radial-gradient-2':
          'radial-gradient(100.44% 141.42% at 0% 0%, var(--grayA1) 0%, var(--grayA6) 100%);',
        'radial-gradient': 'radial-gradient(var(--tw-gradient-stops));',
        'conic-gradient':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
      colors: {
        amber: {
          1: 'var(--amber1)',
          2: 'var(--amber2)',
          3: 'var(--amber3)',
          4: 'var(--amber4)',
          5: 'var(--amber5)',
          6: 'var(--amber6)',
          7: 'var(--amber7)',
          8: 'var(--amber8)',
          9: 'var(--amber9)',
          10: 'var(--amber10)',
          11: 'var(--amber11)',
          12: 'var(--amber12)',
          a1: 'var(--amberA1)',
          a2: 'var(--amberA2)',
          a3: 'var(--amberA3)',
          a4: 'var(--amberA4)',
          a5: 'var(--amberA5)',
          a6: 'var(--amberA6)',
          a7: 'var(--amberA7)',
          a8: 'var(--amberA8)',
          a9: 'var(--amberA9)',
          a10: 'var(--amberA10)',
          a11: 'var(--amberA11)',
          a12: 'var(--amberA12)',
        },
        blue: {
          1: 'var(--blue1)',
          2: 'var(--blue2)',
          3: 'var(--blue3)',
          4: 'var(--blue4)',
          5: 'var(--blue5)',
          6: 'var(--blue6)',
          7: 'var(--blue7)',
          8: 'var(--blue8)',
          9: 'var(--blue9)',
          10: 'var(--blue10)',
          11: 'var(--blue11)',
          12: 'var(--blue12)',
          a1: 'var(--blueA1)',
          a2: 'var(--blueA2)',
          a3: 'var(--blueA3)',
          a4: 'var(--blueA4)',
          a5: 'var(--blueA5)',
          a6: 'var(--blueA6)',
          a7: 'var(--blueA7)',
          a8: 'var(--blueA8)',
          a9: 'var(--blueA9)',
          a10: 'var(--blueA10)',
          a11: 'var(--blueA11)',
          a12: 'var(--blueA12)',
        },
        bronze: {
          1: 'var(--bronze1)',
          2: 'var(--bronze2)',
          3: 'var(--bronze3)',
          4: 'var(--bronze4)',
          5: 'var(--bronze5)',
          6: 'var(--bronze6)',
          7: 'var(--bronze7)',
          8: 'var(--bronze8)',
          9: 'var(--bronze9)',
          10: 'var(--bronze10)',
          11: 'var(--bronze11)',
          12: 'var(--bronze12)',
          a1: 'var(--bronzeA1)',
          a2: 'var(--bronzeA2)',
          a3: 'var(--bronzeA3)',
          a4: 'var(--bronzeA4)',
          a5: 'var(--bronzeA5)',
          a6: 'var(--bronzeA6)',
          a7: 'var(--bronzeA7)',
          a8: 'var(--bronzeA8)',
          a9: 'var(--bronzeA9)',
          a10: 'var(--bronzeA10)',
          a11: 'var(--bronzeA11)',
          a12: 'var(--bronzeA12)',
        },
        brown: {
          1: 'var(--brown1)',
          2: 'var(--brown2)',
          3: 'var(--brown3)',
          4: 'var(--brown4)',
          5: 'var(--brown5)',
          6: 'var(--brown6)',
          7: 'var(--brown7)',
          8: 'var(--brown8)',
          9: 'var(--brown9)',
          10: 'var(--brown10)',
          11: 'var(--brown11)',
          12: 'var(--brown12)',
          a1: 'var(--brownA1)',
          a2: 'var(--brownA2)',
          a3: 'var(--brownA3)',
          a4: 'var(--brownA4)',
          a5: 'var(--brownA5)',
          a6: 'var(--brownA6)',
          a7: 'var(--brownA7)',
          a8: 'var(--brownA8)',
          a9: 'var(--brownA9)',
          a10: 'var(--brownA10)',
          a11: 'var(--brownA11)',
          a12: 'var(--brownA12)',
        },
        crimson: {
          1: 'var(--crimson1)',
          2: 'var(--crimson2)',
          3: 'var(--crimson3)',
          4: 'var(--crimson4)',
          5: 'var(--crimson5)',
          6: 'var(--crimson6)',
          7: 'var(--crimson7)',
          8: 'var(--crimson8)',
          9: 'var(--crimson9)',
          10: 'var(--crimson10)',
          11: 'var(--crimson11)',
          12: 'var(--crimson12)',
          a1: 'var(--crimsonA1)',
          a2: 'var(--crimsonA2)',
          a3: 'var(--crimsonA3)',
          a4: 'var(--crimsonA4)',
          a5: 'var(--crimsonA5)',
          a6: 'var(--crimsonA6)',
          a7: 'var(--crimsonA7)',
          a8: 'var(--crimsonA8)',
          a9: 'var(--crimsonA9)',
          a10: 'var(--crimsonA10)',
          a11: 'var(--crimsonA11)',
          a12: 'var(--crimsonA12)',
        },
        cyan: {
          1: 'var(--cyan1)',
          2: 'var(--cyan2)',
          3: 'var(--cyan3)',
          4: 'var(--cyan4)',
          5: 'var(--cyan5)',
          6: 'var(--cyan6)',
          7: 'var(--cyan7)',
          8: 'var(--cyan8)',
          9: 'var(--cyan9)',
          10: 'var(--cyan10)',
          11: 'var(--cyan11)',
          12: 'var(--cyan12)',
          a1: 'var(--cyanA1)',
          a2: 'var(--cyanA2)',
          a3: 'var(--cyanA3)',
          a4: 'var(--cyanA4)',
          a5: 'var(--cyanA5)',
          a6: 'var(--cyanA6)',
          a7: 'var(--cyanA7)',
          a8: 'var(--cyanA8)',
          a9: 'var(--cyanA9)',
          a10: 'var(--cyanA10)',
          a11: 'var(--cyanA11)',
          a12: 'var(--cyanA12)',
        },
        gold: {
          1: 'var(--gold1)',
          2: 'var(--gold2)',
          3: 'var(--gold3)',
          4: 'var(--gold4)',
          5: 'var(--gold5)',
          6: 'var(--gold6)',
          7: 'var(--gold7)',
          8: 'var(--gold8)',
          9: 'var(--gold9)',
          10: 'var(--gold10)',
          11: 'var(--gold11)',
          12: 'var(--gold12)',
          a1: 'var(--goldA1)',
          a2: 'var(--goldA2)',
          a3: 'var(--goldA3)',
          a4: 'var(--goldA4)',
          a5: 'var(--goldA5)',
          a6: 'var(--goldA6)',
          a7: 'var(--goldA7)',
          a8: 'var(--goldA8)',
          a9: 'var(--goldA9)',
          a10: 'var(--goldA10)',
          a11: 'var(--goldA11)',
          a12: 'var(--goldA12)',
        },
        grass: {
          1: 'var(--grass1)',
          2: 'var(--grass2)',
          3: 'var(--grass3)',
          4: 'var(--grass4)',
          5: 'var(--grass5)',
          6: 'var(--grass6)',
          7: 'var(--grass7)',
          8: 'var(--grass8)',
          9: 'var(--grass9)',
          10: 'var(--grass10)',
          11: 'var(--grass11)',
          12: 'var(--grass12)',
          a1: 'var(--grassA1)',
          a2: 'var(--grassA2)',
          a3: 'var(--grassA3)',
          a4: 'var(--grassA4)',
          a5: 'var(--grassA5)',
          a6: 'var(--grassA6)',
          a7: 'var(--grassA7)',
          a8: 'var(--grassA8)',
          a9: 'var(--grassA9)',
          a10: 'var(--grassA10)',
          a11: 'var(--grassA11)',
          a12: 'var(--grassA12)',
        },
        green: {
          1: 'var(--green1)',
          2: 'var(--green2)',
          3: 'var(--green3)',
          4: 'var(--green4)',
          5: 'var(--green5)',
          6: 'var(--green6)',
          7: 'var(--green7)',
          8: 'var(--green8)',
          9: 'var(--green9)',
          10: 'var(--green10)',
          11: 'var(--green11)',
          12: 'var(--green12)',
          a1: 'var(--greenA1)',
          a2: 'var(--greenA2)',
          a3: 'var(--greenA3)',
          a4: 'var(--greenA4)',
          a5: 'var(--greenA5)',
          a6: 'var(--greenA6)',
          a7: 'var(--greenA7)',
          a8: 'var(--greenA8)',
          a9: 'var(--greenA9)',
          a10: 'var(--greenA10)',
          a11: 'var(--greenA11)',
          a12: 'var(--greenA12)',
        },
        indigo: {
          1: 'var(--indigo1)',
          2: 'var(--indigo2)',
          3: 'var(--indigo3)',
          4: 'var(--indigo4)',
          5: 'var(--indigo5)',
          6: 'var(--indigo6)',
          7: 'var(--indigo7)',
          8: 'var(--indigo8)',
          9: 'var(--indigo9)',
          10: 'var(--indigo10)',
          11: 'var(--indigo11)',
          12: 'var(--indigo12)',
          a1: 'var(--indigoA1)',
          a2: 'var(--indigoA2)',
          a3: 'var(--indigoA3)',
          a4: 'var(--indigoA4)',
          a5: 'var(--indigoA5)',
          a6: 'var(--indigoA6)',
          a7: 'var(--indigoA7)',
          a8: 'var(--indigoA8)',
          a9: 'var(--indigoA9)',
          a10: 'var(--indigoA10)',
          a11: 'var(--indigoA11)',
          a12: 'var(--indigoA12)',
        },
        iris: {
          1: 'var(--iris1)',
          2: 'var(--iris2)',
          3: 'var(--iris3)',
          4: 'var(--iris4)',
          5: 'var(--iris5)',
          6: 'var(--iris6)',
          7: 'var(--iris7)',
          8: 'var(--iris8)',
          9: 'var(--iris9)',
          10: 'var(--iris10)',
          11: 'var(--iris11)',
          12: 'var(--iris12)',
          a1: 'var(--irisA1)',
          a2: 'var(--irisA2)',
          a3: 'var(--irisA3)',
          a4: 'var(--irisA4)',
          a5: 'var(--irisA5)',
          a6: 'var(--irisA6)',
          a7: 'var(--irisA7)',
          a8: 'var(--irisA8)',
          a9: 'var(--irisA9)',
          a10: 'var(--irisA10)',
          a11: 'var(--irisA11)',
          a12: 'var(--irisA12)',
        },
        jade: {
          1: 'var(--jade1)',
          2: 'var(--jade2)',
          3: 'var(--jade3)',
          4: 'var(--jade4)',
          5: 'var(--jade5)',
          6: 'var(--jade6)',
          7: 'var(--jade7)',
          8: 'var(--jade8)',
          9: 'var(--jade9)',
          10: 'var(--jade10)',
          11: 'var(--jade11)',
          12: 'var(--jade12)',
          a1: 'var(--jadeA1)',
          a2: 'var(--jadeA2)',
          a3: 'var(--jadeA3)',
          a4: 'var(--jadeA4)',
          a5: 'var(--jadeA5)',
          a6: 'var(--jadeA6)',
          a7: 'var(--jadeA7)',
          a8: 'var(--jadeA8)',
          a9: 'var(--jadeA9)',
          a10: 'var(--jadeA10)',
          a11: 'var(--jadeA11)',
          a12: 'var(--jadeA12)',
        },
        lime: {
          1: 'var(--lime1)',
          2: 'var(--lime2)',
          3: 'var(--lime3)',
          4: 'var(--lime4)',
          5: 'var(--lime5)',
          6: 'var(--lime6)',
          7: 'var(--lime7)',
          8: 'var(--lime8)',
          9: 'var(--lime9)',
          10: 'var(--lime10)',
          11: 'var(--lime11)',
          12: 'var(--lime12)',
          a1: 'var(--limeA1)',
          a2: 'var(--limeA2)',
          a3: 'var(--limeA3)',
          a4: 'var(--limeA4)',
          a5: 'var(--limeA5)',
          a6: 'var(--limeA6)',
          a7: 'var(--limeA7)',
          a8: 'var(--limeA8)',
          a9: 'var(--limeA9)',
          a10: 'var(--limeA10)',
          a11: 'var(--limeA11)',
          a12: 'var(--limeA12)',
        },
        mauve: {
          1: 'var(--mauve1)',
          2: 'var(--mauve2)',
          3: 'var(--mauve3)',
          4: 'var(--mauve4)',
          5: 'var(--mauve5)',
          6: 'var(--mauve6)',
          7: 'var(--mauve7)',
          8: 'var(--mauve8)',
          9: 'var(--mauve9)',
          10: 'var(--mauve10)',
          11: 'var(--mauve11)',
          12: 'var(--mauve12)',
          a1: 'var(--mauveA1)',
          a2: 'var(--mauveA2)',
          a3: 'var(--mauveA3)',
          a4: 'var(--mauveA4)',
          a5: 'var(--mauveA5)',
          a6: 'var(--mauveA6)',
          a7: 'var(--mauveA7)',
          a8: 'var(--mauveA8)',
          a9: 'var(--mauveA9)',
          a10: 'var(--mauveA10)',
          a11: 'var(--mauveA11)',
          a12: 'var(--mauveA12)',
        },
        mint: {
          1: 'var(--mint1)',
          2: 'var(--mint2)',
          3: 'var(--mint3)',
          4: 'var(--mint4)',
          5: 'var(--mint5)',
          6: 'var(--mint6)',
          7: 'var(--mint7)',
          8: 'var(--mint8)',
          9: 'var(--mint9)',
          10: 'var(--mint10)',
          11: 'var(--mint11)',
          12: 'var(--mint12)',
          a1: 'var(--mintA1)',
          a2: 'var(--mintA2)',
          a3: 'var(--mintA3)',
          a4: 'var(--mintA4)',
          a5: 'var(--mintA5)',
          a6: 'var(--mintA6)',
          a7: 'var(--mintA7)',
          a8: 'var(--mintA8)',
          a9: 'var(--mintA9)',
          a10: 'var(--mintA10)',
          a11: 'var(--mintA11)',
          a12: 'var(--mintA12)',
        },
        olive: {
          1: 'var(--olive1)',
          2: 'var(--olive2)',
          3: 'var(--olive3)',
          4: 'var(--olive4)',
          5: 'var(--olive5)',
          6: 'var(--olive6)',
          7: 'var(--olive7)',
          8: 'var(--olive8)',
          9: 'var(--olive9)',
          10: 'var(--olive10)',
          11: 'var(--olive11)',
          12: 'var(--olive12)',
          a1: 'var(--oliveA1)',
          a2: 'var(--oliveA2)',
          a3: 'var(--oliveA3)',
          a4: 'var(--oliveA4)',
          a5: 'var(--oliveA5)',
          a6: 'var(--oliveA6)',
          a7: 'var(--oliveA7)',
          a8: 'var(--oliveA8)',
          a9: 'var(--oliveA9)',
          a10: 'var(--oliveA10)',
          a11: 'var(--oliveA11)',
          a12: 'var(--oliveA12)',
        },
        orange: {
          1: 'var(--orange1)',
          2: 'var(--orange2)',
          3: 'var(--orange3)',
          4: 'var(--orange4)',
          5: 'var(--orange5)',
          6: 'var(--orange6)',
          7: 'var(--orange7)',
          8: 'var(--orange8)',
          9: 'var(--orange9)',
          10: 'var(--orange10)',
          11: 'var(--orange11)',
          12: 'var(--orange12)',
          a1: 'var(--orangeA1)',
          a2: 'var(--orangeA2)',
          a3: 'var(--orangeA3)',
          a4: 'var(--orangeA4)',
          a5: 'var(--orangeA5)',
          a6: 'var(--orangeA6)',
          a7: 'var(--orangeA7)',
          a8: 'var(--orangeA8)',
          a9: 'var(--orangeA9)',
          a10: 'var(--orangeA10)',
          a11: 'var(--orangeA11)',
          a12: 'var(--orangeA12)',
        },
        pink: {
          1: 'var(--pink1)',
          2: 'var(--pink2)',
          3: 'var(--pink3)',
          4: 'var(--pink4)',
          5: 'var(--pink5)',
          6: 'var(--pink6)',
          7: 'var(--pink7)',
          8: 'var(--pink8)',
          9: 'var(--pink9)',
          10: 'var(--pink10)',
          11: 'var(--pink11)',
          12: 'var(--pink12)',
          a1: 'var(--pinkA1)',
          a2: 'var(--pinkA2)',
          a3: 'var(--pinkA3)',
          a4: 'var(--pinkA4)',
          a5: 'var(--pinkA5)',
          a6: 'var(--pinkA6)',
          a7: 'var(--pinkA7)',
          a8: 'var(--pinkA8)',
          a9: 'var(--pinkA9)',
          a10: 'var(--pinkA10)',
          a11: 'var(--pinkA11)',
          a12: 'var(--pinkA12)',
        },
        plum: {
          1: 'var(--plum1)',
          2: 'var(--plum2)',
          3: 'var(--plum3)',
          4: 'var(--plum4)',
          5: 'var(--plum5)',
          6: 'var(--plum6)',
          7: 'var(--plum7)',
          8: 'var(--plum8)',
          9: 'var(--plum9)',
          10: 'var(--plum10)',
          11: 'var(--plum11)',
          12: 'var(--plum12)',
          a1: 'var(--plumA1)',
          a2: 'var(--plumA2)',
          a3: 'var(--plumA3)',
          a4: 'var(--plumA4)',
          a5: 'var(--plumA5)',
          a6: 'var(--plumA6)',
          a7: 'var(--plumA7)',
          a8: 'var(--plumA8)',
          a9: 'var(--plumA9)',
          a10: 'var(--plumA10)',
          a11: 'var(--plumA11)',
          a12: 'var(--plumA12)',
        },
        purple: {
          1: 'var(--purple1)',
          2: 'var(--purple2)',
          3: 'var(--purple3)',
          4: 'var(--purple4)',
          5: 'var(--purple5)',
          6: 'var(--purple6)',
          7: 'var(--purple7)',
          8: 'var(--purple8)',
          9: 'var(--purple9)',
          10: 'var(--purple10)',
          11: 'var(--purple11)',
          12: 'var(--purple12)',
          a1: 'var(--purpleA1)',
          a2: 'var(--purpleA2)',
          a3: 'var(--purpleA3)',
          a4: 'var(--purpleA4)',
          a5: 'var(--purpleA5)',
          a6: 'var(--purpleA6)',
          a7: 'var(--purpleA7)',
          a8: 'var(--purpleA8)',
          a9: 'var(--purpleA9)',
          a10: 'var(--purpleA10)',
          a11: 'var(--purpleA11)',
          a12: 'var(--purpleA12)',
        },
        red: {
          1: 'var(--red1)',
          2: 'var(--red2)',
          3: 'var(--red3)',
          4: 'var(--red4)',
          5: 'var(--red5)',
          6: 'var(--red6)',
          7: 'var(--red7)',
          8: 'var(--red8)',
          9: 'var(--red9)',
          10: 'var(--red10)',
          11: 'var(--red11)',
          12: 'var(--red12)',
          a1: 'var(--redA1)',
          a2: 'var(--redA2)',
          a3: 'var(--redA3)',
          a4: 'var(--redA4)',
          a5: 'var(--redA5)',
          a6: 'var(--redA6)',
          a7: 'var(--redA7)',
          a8: 'var(--redA8)',
          a9: 'var(--redA9)',
          a10: 'var(--redA10)',
          a11: 'var(--redA11)',
          a12: 'var(--redA12)',
        },
        ruby: {
          1: 'var(--ruby1)',
          2: 'var(--ruby2)',
          3: 'var(--ruby3)',
          4: 'var(--ruby4)',
          5: 'var(--ruby5)',
          6: 'var(--ruby6)',
          7: 'var(--ruby7)',
          8: 'var(--ruby8)',
          9: 'var(--ruby9)',
          10: 'var(--ruby10)',
          11: 'var(--ruby11)',
          12: 'var(--ruby12)',
          a1: 'var(--rubyA1)',
          a2: 'var(--rubyA2)',
          a3: 'var(--rubyA3)',
          a4: 'var(--rubyA4)',
          a5: 'var(--rubyA5)',
          a6: 'var(--rubyA6)',
          a7: 'var(--rubyA7)',
          a8: 'var(--rubyA8)',
          a9: 'var(--rubyA9)',
          a10: 'var(--rubyA10)',
          a11: 'var(--rubyA11)',
          a12: 'var(--rubyA12)',
        },
        sage: {
          1: 'var(--sage1)',
          2: 'var(--sage2)',
          3: 'var(--sage3)',
          4: 'var(--sage4)',
          5: 'var(--sage5)',
          6: 'var(--sage6)',
          7: 'var(--sage7)',
          8: 'var(--sage8)',
          9: 'var(--sage9)',
          10: 'var(--sage10)',
          11: 'var(--sage11)',
          12: 'var(--sage12)',
          a1: 'var(--sageA1)',
          a2: 'var(--sageA2)',
          a3: 'var(--sageA3)',
          a4: 'var(--sageA4)',
          a5: 'var(--sageA5)',
          a6: 'var(--sageA6)',
          a7: 'var(--sageA7)',
          a8: 'var(--sageA8)',
          a9: 'var(--sageA9)',
          a10: 'var(--sageA10)',
          a11: 'var(--sageA11)',
          a12: 'var(--sageA12)',
        },
        sand: {
          1: 'var(--sand1)',
          2: 'var(--sand2)',
          3: 'var(--sand3)',
          4: 'var(--sand4)',
          5: 'var(--sand5)',
          6: 'var(--sand6)',
          7: 'var(--sand7)',
          8: 'var(--sand8)',
          9: 'var(--sand9)',
          10: 'var(--sand10)',
          11: 'var(--sand11)',
          12: 'var(--sand12)',
          a1: 'var(--sandA1)',
          a2: 'var(--sandA2)',
          a3: 'var(--sandA3)',
          a4: 'var(--sandA4)',
          a5: 'var(--sandA5)',
          a6: 'var(--sandA6)',
          a7: 'var(--sandA7)',
          a8: 'var(--sandA8)',
          a9: 'var(--sandA9)',
          a10: 'var(--sandA10)',
          a11: 'var(--sandA11)',
          a12: 'var(--sandA12)',
        },
        sky: {
          1: 'var(--sky1)',
          2: 'var(--sky2)',
          3: 'var(--sky3)',
          4: 'var(--sky4)',
          5: 'var(--sky5)',
          6: 'var(--sky6)',
          7: 'var(--sky7)',
          8: 'var(--sky8)',
          9: 'var(--sky9)',
          10: 'var(--sky10)',
          11: 'var(--sky11)',
          12: 'var(--sky12)',
          a1: 'var(--skyA1)',
          a2: 'var(--skyA2)',
          a3: 'var(--skyA3)',
          a4: 'var(--skyA4)',
          a5: 'var(--skyA5)',
          a6: 'var(--skyA6)',
          a7: 'var(--skyA7)',
          a8: 'var(--skyA8)',
          a9: 'var(--skyA9)',
          a10: 'var(--skyA10)',
          a11: 'var(--skyA11)',
          a12: 'var(--skyA12)',
        },
        slate: {
          1: 'var(--slate1)',
          2: 'var(--slate2)',
          3: 'var(--slate3)',
          4: 'var(--slate4)',
          5: 'var(--slate5)',
          6: 'var(--slate6)',
          7: 'var(--slate7)',
          8: 'var(--slate8)',
          9: 'var(--slate9)',
          10: 'var(--slate10)',
          11: 'var(--slate11)',
          12: 'var(--slate12)',
          a1: 'var(--slateA1)',
          a2: 'var(--slateA2)',
          a3: 'var(--slateA3)',
          a4: 'var(--slateA4)',
          a5: 'var(--slateA5)',
          a6: 'var(--slateA6)',
          a7: 'var(--slateA7)',
          a8: 'var(--slateA8)',
          a9: 'var(--slateA9)',
          a10: 'var(--slateA10)',
          a11: 'var(--slateA11)',
          a12: 'var(--slateA12)',
        },
        teal: {
          1: 'var(--teal1)',
          2: 'var(--teal2)',
          3: 'var(--teal3)',
          4: 'var(--teal4)',
          5: 'var(--teal5)',
          6: 'var(--teal6)',
          7: 'var(--teal7)',
          8: 'var(--teal8)',
          9: 'var(--teal9)',
          10: 'var(--teal10)',
          11: 'var(--teal11)',
          12: 'var(--teal12)',
          a1: 'var(--tealA1)',
          a2: 'var(--tealA2)',
          a3: 'var(--tealA3)',
          a4: 'var(--tealA4)',
          a5: 'var(--tealA5)',
          a6: 'var(--tealA6)',
          a7: 'var(--tealA7)',
          a8: 'var(--tealA8)',
          a9: 'var(--tealA9)',
          a10: 'var(--tealA10)',
          a11: 'var(--tealA11)',
          a12: 'var(--tealA12)',
        },
        tomato: {
          1: 'var(--tomato1)',
          2: 'var(--tomato2)',
          3: 'var(--tomato3)',
          4: 'var(--tomato4)',
          5: 'var(--tomato5)',
          6: 'var(--tomato6)',
          7: 'var(--tomato7)',
          8: 'var(--tomato8)',
          9: 'var(--tomato9)',
          10: 'var(--tomato10)',
          11: 'var(--tomato11)',
          12: 'var(--tomato12)',
          a1: 'var(--tomatoA1)',
          a2: 'var(--tomatoA2)',
          a3: 'var(--tomatoA3)',
          a4: 'var(--tomatoA4)',
          a5: 'var(--tomatoA5)',
          a6: 'var(--tomatoA6)',
          a7: 'var(--tomatoA7)',
          a8: 'var(--tomatoA8)',
          a9: 'var(--tomatoA9)',
          a10: 'var(--tomatoA10)',
          a11: 'var(--tomatoA11)',
          a12: 'var(--tomatoA12)',
        },
        violet: {
          1: 'var(--violet1)',
          2: 'var(--violet2)',
          3: 'var(--violet3)',
          4: 'var(--violet4)',
          5: 'var(--violet5)',
          6: 'var(--violet6)',
          7: 'var(--violet7)',
          8: 'var(--violet8)',
          9: 'var(--violet9)',
          10: 'var(--violet10)',
          11: 'var(--violet11)',
          12: 'var(--violet12)',
          a1: 'var(--violetA1)',
          a2: 'var(--violetA2)',
          a3: 'var(--violetA3)',
          a4: 'var(--violetA4)',
          a5: 'var(--violetA5)',
          a6: 'var(--violetA6)',
          a7: 'var(--violetA7)',
          a8: 'var(--violetA8)',
          a9: 'var(--violetA9)',
          a10: 'var(--violetA10)',
          a11: 'var(--violetA11)',
          a12: 'var(--violetA12)',
        },
        yellow: {
          1: 'var(--yellow1)',
          2: 'var(--yellow2)',
          3: 'var(--yellow3)',
          4: 'var(--yellow4)',
          5: 'var(--yellow5)',
          6: 'var(--yellow6)',
          7: 'var(--yellow7)',
          8: 'var(--yellow8)',
          9: 'var(--yellow9)',
          10: 'var(--yellow10)',
          11: 'var(--yellow11)',
          12: 'var(--yellow12)',
          a1: 'var(--yellowA1)',
          a2: 'var(--yellowA2)',
          a3: 'var(--yellowA3)',
          a4: 'var(--yellowA4)',
          a5: 'var(--yellowA5)',
          a6: 'var(--yellowA6)',
          a7: 'var(--yellowA7)',
          a8: 'var(--yellowA8)',
          a9: 'var(--yellowA9)',
          a10: 'var(--yellowA10)',
          a11: 'var(--yellowA11)',
          a12: 'var(--yellowA12)',
        },
        white: {
          a1: 'var(--whiteA1)',
          a2: 'var(--whiteA2)',
          a3: 'var(--whiteA3)',
          a4: 'var(--whiteA4)',
          a5: 'var(--whiteA5)',
          a6: 'var(--whiteA6)',
          a7: 'var(--whiteA7)',
          a8: 'var(--whiteA8)',
          a9: 'var(--whiteA9)',
          a10: 'var(--whiteA10)',
          a11: 'var(--whiteA11)',
          a12: 'var(--whiteA12)',
        },
        black: {
          a1: 'var(--blackA1)',
          a2: 'var(--blackA2)',
          a3: 'var(--blackA3)',
          a4: 'var(--blackA4)',
          a5: 'var(--blackA5)',
          a6: 'var(--blackA6)',
          a7: 'var(--blackA7)',
          a8: 'var(--blackA8)',
          a9: 'var(--blackA9)',
          a10: 'var(--blackA10)',
          a11: 'var(--blackA11)',
          a12: 'var(--blackA12)',
        },
        background: 'var(--gray2)',
        foreground: 'var(--gray12)',

        muted: {
          DEFAULT: 'var(--gray4)',
          foreground: 'var(--gray11)',
        },

        card: {
          DEFAULT: 'hsl(var(--gray2))',
          foreground: 'var(--gray11)',
        },

        popover: {
          // DEFAULT: 'hsl(var(--gray9))',
          DEFAULT: 'var(--gray3)',
          foreground: 'var(--gray11)',
        },

        input: 'var(--gray4)',

        accent: {
          DEFAULT: 'var(--accent11)',
          hover: 'var(--accent12)',
          selected: 'var(--accent12)',
          foreground: 'var(--accent2)',
          1: 'var(--accent1)',
          2: 'var(--accent2)',
          3: 'var(--accent3)',
          4: 'var(--accent4)',
          5: 'var(--accent5)',
          6: 'var(--accent6)',
          7: 'var(--accent7)',
          8: 'var(--accent8)',
          9: 'var(--accent9)',
          10: 'var(--accent10)',
          11: 'var(--accent11)',
          12: 'var(--accent12)',
        },

        gray: {
          DEFAULT: 'var(--gray11)',
          hover: 'var(--gray12)',
          selected: 'var(--gray12)',
          foreground: 'var(--gray2)',
          1: 'var(--gray1)',
          2: 'var(--gray2)',
          3: 'var(--gray3)',
          4: 'var(--gray4)',
          5: 'var(--gray5)',
          6: 'var(--gray6)',
          7: 'var(--gray7)',
          8: 'var(--gray8)',
          9: 'var(--gray9)',
          10: 'var(--gray10)',
          11: 'var(--gray11)',
          12: 'var(--gray12)',
        },

        primary: {
          DEFAULT: 'var(--violet9)',
          foreground: 'var(--violet1)',
          1: 'var(--violet1)',
          2: 'var(--violet2)',
          3: 'var(--violet3)',
          4: 'var(--violet4)',
          5: 'var(--violet5)',
          6: 'var(--violet6)',
          7: 'var(--violet7)',
          8: 'var(--violet8)',
          9: 'var(--violet9)',
          10: 'var(--violet10)',
          11: 'var(--violet11)',
          12: 'var(--violet12)',
        },

        ghost: {
          DEFAULT: 'var(--ghost-a2)',
          a1: 'var(--ghost-a1)',
          a2: 'var(--ghost-a2)',
          a3: 'var(--ghost-a3)',
          a4: 'var(--ghost-a4)',
          a5: 'var(--ghost-a5)',
          a6: 'var(--ghost-a6)',
          a7: 'var(--ghost-a7)',
          a8: 'var(--ghost-a8)',
          a9: 'var(--ghost-a9)',
          a10: 'var(--ghost-a10)',
          a11: 'var(--ghost-a11)',
          a12: 'var(--ghost-a12)',
          aa1: 'var(--ghost-aa1)',
          aa2: 'var(--ghost-aa2)',
          aa3: 'var(--ghost-aa3)',
          aa4: 'var(--ghost-aa4)',
          aa5: 'var(--ghost-aa5)',
          aa6: 'var(--ghost-aa6)',
          aa7: 'var(--ghost-aa7)',
          aa8: 'var(--ghost-aa8)',
          aa9: 'var(--ghost-aa9)',
          aa10: 'var(--ghost-aa10)',
          aa11: 'var(--ghost-aa11)',
          aa12: 'var(--ghost-aa12)',
          1: 'var(--ghost-1)',
          2: 'var(--ghost-2)',
          3: 'var(--ghost-3)',
          4: 'var(--ghost-4)',
          5: 'var(--ghost-5)',
          6: 'var(--ghost-6)',
          7: 'var(--ghost-7)',
          8: 'var(--ghost-8)',
          9: 'var(--ghost-9)',
          10: 'var(--ghost-10)',
          11: 'var(--ghost-11)',
          12: 'var(--ghost-12)',
        },

        secondary: {
          DEFAULT: 'var(--blue10)',
          foreground: 'var(--blue1)',
          1: 'var(--blue1)',
          2: 'var(--blue2)',
          3: 'var(--blue3)',
          4: 'var(--blue4)',
          5: 'var(--blue5)',
          6: 'var(--blue6)',
          7: 'var(--blue7)',
          8: 'var(--blue8)',
          9: 'var(--blue9)',
          10: 'var(--blue10)',
          11: 'var(--blue11)',
          12: 'var(--blue12)',
        },

        destructive: {
          DEFAULT: 'var(--red9)',
          foreground: 'var(--red1)',
          1: 'var(--red1)',
          2: 'var(--red2)',
          3: 'var(--red3)',
          4: 'var(--red4)',
          5: 'var(--red5)',
          6: 'var(--red6)',
          7: 'var(--red7)',
          8: 'var(--red8)',
          9: 'var(--red9)',
          10: 'var(--red10)',
          11: 'var(--red11)',
          12: 'var(--red12)',
        },

        border: 'var(--grayA4)',
        ring: 'var(--grayA4)',
      },
      borderRadius: {
        radius: '0.5rem',
      },
      fontFamily: {
        sans: ['var(--font-theme-sans)'],
        mono: ['var(--font-theme-mono)'],
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        'caret-blink': {
          '0%,70%,100%': { opacity: '1' },
          '20%,50%': { opacity: '0' },
        },
        marquee: {
          from: { transform: 'translateX(0)' },
          to: { transform: 'translateX(calc(-100% - var(--gap)))' },
        },
        'marquee-vertical': {
          from: { transform: 'translateY(0)' },
          to: { transform: 'translateY(calc(-100% - var(--gap)))' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'caret-blink': 'caret-blink 1.25s ease-out infinite',
        spinSlow1x: 'spin 20.25s linear infinite',
        spinSlow2x: 'spin 22.25s linear infinite',
        spinSlow3x: 'spin 24.25s linear infinite',
        spinSlow4x: 'spin 26.25s linear infinite',
        marquee: 'marquee var(--duration) linear infinite',
        'marquee-vertical': 'marquee-vertical var(--duration) linear infinite',
        'border-beam': 'border-beam calc(var(--duration)*1s) infinite linear',
      },
      transitionDelay: {
        0: '0s',
        75: '75ms',
        100: '100ms',
        150: '150ms',
        200: '200ms',
        300: '300ms',
        500: '500ms',
        700: '700ms',
        1000: '1000ms',
        2000: '2000ms',
        3000: '3000ms',
        4000: '4000ms',
        5000: '5000ms',
        6000: '6000ms',
        7000: '7000ms',
        8000: '8000ms',
        9000: '9000ms',
        10000: '10000ms',
      },
      transitionDuration: {
        DEFAULT: '150ms',
        0: '0s',
        75: '75ms',
        100: '100ms',
        150: '150ms',
        200: '200ms',
        300: '300ms',
        500: '500ms',
        700: '700ms',
        1000: '1000ms',
        2000: '2000ms',
        3000: '3000ms',
        4000: '4000ms',
        5000: '5000ms',
        6000: '6000ms',
        7000: '7000ms',
        8000: '8000ms',
        9000: '9000ms',
        10000: '10000ms',
      },
      transitionProperty: {
        none: 'none',
        all: 'all',
        DEFAULT:
          'color, background-color, border-color, text-decoration-color, fill, stroke, opacity, box-shadow, transform, filter, backdrop-filter',
        colors:
          'color, background-color, border-color, text-decoration-color, fill, stroke',
        opacity: 'opacity',
        shadow: 'box-shadow',
        transform: 'transform',
      },
      transitionTimingFunction: {
        DEFAULT: 'cubic-bezier(0.4, 0, 0.2, 1)',
        linear: 'linear',
        in: 'cubic-bezier(0.4, 0, 1, 1)',
        out: 'cubic-bezier(0, 0, 0.2, 1)',
        'in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      width: {
        auto: 'auto',
        '1/2': '50%',
        '1/3': '33.333333%',
        '2/3': '66.666667%',
        '1/4': '25%',
        '2/4': '50%',
        '3/4': '75%',
        '1/5': '20%',
        '2/5': '40%',
        '3/5': '60%',
        '4/5': '80%',
        '1/6': '16.666667%',
        '2/6': '33.333333%',
        '3/6': '50%',
        '4/6': '66.666667%',
        '5/6': '83.333333%',
        '1/12': '8.333333%',
        '2/12': '16.666667%',
        '3/12': '25%',
        '4/12': '33.333333%',
        '5/12': '41.666667%',
        '6/12': '50%',
        '7/12': '58.333333%',
        '8/12': '66.666667%',
        '9/12': '75%',
        '10/12': '83.333333%',
        '11/12': '91.666667%',
        full: '100%',
        '2full': '200%',
        screen: '100vw',
      },
    },
  },
  plugins: [
    // biome-ignore lint/suspicious/noExplicitAny: <explanation>
    plugin(({ matchUtilities, theme }: any) => {
      matchUtilities(
        {
          // biome-ignore lint/suspicious/noExplicitAny: <explanation>
          'translate-z': (value: any) => ({
            '--tw-translate-z': value,
            transform:
              ' translate3d(var(--tw-translate-x), var(--tw-translate-y), var(--tw-translate-z)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))',
          }), // this is actual CSS
          // biome-ignore lint/suspicious/noExplicitAny: <explanation>
          'text-shadow': (value: any) => ({
            textShadow: value,
          }),
        },
        { values: theme('textShadow') },
        { values: theme('translate'), supportsNegativeValues: true },
      )
    }),
    // biome-ignore lint/suspicious/noExplicitAny: <explanation>
    plugin(({ addUtilities }: any) => {
      const newUtilities = {
        '.text-shadow-glow': {
          textShadow:
            '0 0 5px rgba(0, 255, 0, 0.7), 0 0 10px rgba(0, 255, 0, 0.5)',
        },
      }
      addUtilities(newUtilities)
    }),
    animate,
    typography,
    forms,
    aspectRatio,
    {
      config: colors.plugin.config ?? {},
      handler: colors.plugin.handler,
    },
    {
      config: containerQueries.config ?? {},
      handler: containerQueries.handler,
    },
  ],
}
