import type { Config } from 'tailwindcss'

import aspectRatio from '@tailwindcss/aspect-ratio'
import containerQueries from '@tailwindcss/container-queries'
import forms from '@tailwindcss/forms'
import typography from '@tailwindcss/typography'
import animate from 'tailwindcss-animate'
import { createPlugin } from 'windy-radix-palette'
import windyTypography from 'windy-radix-typography'

const colors = createPlugin()

export const prodktTailwindPreset: Config = {
  content: ['./src/**/*.{js,jsx,ts,tsx,mdx}'],
  presets: [windyTypography],
  theme: {
    extend: {
      backgroundImage: {
        'radial-gradient-1':
          'radial-gradient(87.07% 87.07% at 52.38% 100%, var(--grayA1) 0%, var(--grayA6) 100%)',
        'radial-gradient-2':
          'radial-gradient(100.44% 141.42% at 0% 0%, var(--grayA1) 0%, var(--grayA6) 100%);',
      },
      colors: {
        background: 'var(--gray1)',
        foreground: 'var(--gray12)',

        muted: {
          DEFAULT: 'var(--gray4)',
          foreground: 'var(--gray11)',
        },

        card: {
          DEFAULT: 'hsl(var(--gray2))',
          foreground: 'var(--gray11)',
        },

        popover: {
          // DEFAULT: 'hsl(var(--gray9))',
          DEFAULT: 'var(--gray3)',
          foreground: 'var(--gray11)',
        },

        input: 'var(--gray4)',

        accent: {
          DEFAULT: 'var(--accent11)',
          hover: 'var(--accent12)',
          selected: 'var(--accent12)',
          foreground: 'var(--accent2)',
          1: 'var(--accent1)',
          2: 'var(--accent2)',
          3: 'var(--accent3)',
          4: 'var(--accent4)',
          5: 'var(--accent5)',
          6: 'var(--accent6)',
          7: 'var(--accent7)',
          8: 'var(--accent8)',
          9: 'var(--accent9)',
          10: 'var(--accent10)',
          11: 'var(--accent11)',
          12: 'var(--accent12)',
        },

        gray: {
          DEFAULT: 'var(--gray11)',
          hover: 'var(--gray12)',
          selected: 'var(--gray12)',
          foreground: 'var(--gray2)',
          1: 'var(--gray1)',
          2: 'var(--gray2)',
          3: 'var(--gray3)',
          4: 'var(--gray4)',
          5: 'var(--gray5)',
          6: 'var(--gray6)',
          7: 'var(--gray7)',
          8: 'var(--gray8)',
          9: 'var(--gray9)',
          10: 'var(--gray10)',
          11: 'var(--gray11)',
          12: 'var(--gray12)',
        },

        primary: {
          DEFAULT: 'var(--violet9)',
          foreground: 'var(--violet1)',
          1: 'var(--violet1)',
          2: 'var(--violet2)',
          3: 'var(--violet3)',
          4: 'var(--violet4)',
          5: 'var(--violet5)',
          6: 'var(--violet6)',
          7: 'var(--violet7)',
          8: 'var(--violet8)',
          9: 'var(--violet9)',
          10: 'var(--violet10)',
          11: 'var(--violet11)',
          12: 'var(--violet12)',
        },

        ghost: {
          DEFAULT: 'var(--ghost-a2)',
          a1: 'var(--ghost-a1)',
          a2: 'var(--ghost-a2)',
          a3: 'var(--ghost-a3)',
          a4: 'var(--ghost-a4)',
          a5: 'var(--ghost-a5)',
          a6: 'var(--ghost-a6)',
          a7: 'var(--ghost-a7)',
          a8: 'var(--ghost-a8)',
          a9: 'var(--ghost-a9)',
          a10: 'var(--ghost-a10)',
          a11: 'var(--ghost-a11)',
          a12: 'var(--ghost-a12)',
          aa1: 'var(--ghost-aa1)',
          aa2: 'var(--ghost-aa2)',
          aa3: 'var(--ghost-aa3)',
          aa4: 'var(--ghost-aa4)',
          aa5: 'var(--ghost-aa5)',
          aa6: 'var(--ghost-aa6)',
          aa7: 'var(--ghost-aa7)',
          aa8: 'var(--ghost-aa8)',
          aa9: 'var(--ghost-aa9)',
          aa10: 'var(--ghost-aa10)',
          aa11: 'var(--ghost-aa11)',
          aa12: 'var(--ghost-aa12)',
          1: 'var(--ghost-1)',
          2: 'var(--ghost-2)',
          3: 'var(--ghost-3)',
          4: 'var(--ghost-4)',
          5: 'var(--ghost-5)',
          6: 'var(--ghost-6)',
          7: 'var(--ghost-7)',
          8: 'var(--ghost-8)',
          9: 'var(--ghost-9)',
          10: 'var(--ghost-10)',
          11: 'var(--ghost-11)',
          12: 'var(--ghost-12)',
        },

        secondary: {
          DEFAULT: 'var(--blue10)',
          foreground: 'var(--blue1)',
          1: 'var(--blue1)',
          2: 'var(--blue2)',
          3: 'var(--blue3)',
          4: 'var(--blue4)',
          5: 'var(--blue5)',
          6: 'var(--blue6)',
          7: 'var(--blue7)',
          8: 'var(--blue8)',
          9: 'var(--blue9)',
          10: 'var(--blue10)',
          11: 'var(--blue11)',
          12: 'var(--blue12)',
        },

        destructive: {
          DEFAULT: 'var(--red9)',
          foreground: 'var(--red1)',
          1: 'var(--red1)',
          2: 'var(--red2)',
          3: 'var(--red3)',
          4: 'var(--red4)',
          5: 'var(--red5)',
          6: 'var(--red6)',
          7: 'var(--red7)',
          8: 'var(--red8)',
          9: 'var(--red9)',
          10: 'var(--red10)',
          11: 'var(--red11)',
          12: 'var(--red12)',
        },

        border: 'var(--gray4)',
        ring: 'var(--gray4)',
      },
      borderRadius: {
        radius: '0.5rem',
      },
      fontFamily: {
        sans: ['var(--font-labil-grotesk)'],
        mono: ['var(--font-ibm-plex-mono)'],
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        'caret-blink': {
          '0%,70%,100%': { opacity: '1' },
          '20%,50%': { opacity: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'caret-blink': 'caret-blink 1.25s ease-out infinite',
        spinSlow1x: 'spin 20.25s linear infinite',
        spinSlow2x: 'spin 22.25s linear infinite',
        spinSlow3x: 'spin 24.25s linear infinite',
        spinSlow4x: 'spin 26.25s linear infinite',
      },
      transitionDelay: {
        0: '0s',
        75: '75ms',
        100: '100ms',
        150: '150ms',
        200: '200ms',
        300: '300ms',
        500: '500ms',
        700: '700ms',
        1000: '1000ms',
      },
      transitionDuration: {
        DEFAULT: '150ms',
        0: '0s',
        75: '75ms',
        100: '100ms',
        150: '150ms',
        200: '200ms',
        300: '300ms',
        500: '500ms',
        700: '700ms',
        1000: '1000ms',
      },
      transitionProperty: {
        none: 'none',
        all: 'all',
        DEFAULT:
          'color, background-color, border-color, text-decoration-color, fill, stroke, opacity, box-shadow, transform, filter, backdrop-filter',
        colors:
          'color, background-color, border-color, text-decoration-color, fill, stroke',
        opacity: 'opacity',
        shadow: 'box-shadow',
        transform: 'transform',
      },
      transitionTimingFunction: {
        DEFAULT: 'cubic-bezier(0.4, 0, 0.2, 1)',
        linear: 'linear',
        in: 'cubic-bezier(0.4, 0, 1, 1)',
        out: 'cubic-bezier(0, 0, 0.2, 1)',
        'in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      width: {
        auto: 'auto',
        '1/2': '50%',
        '1/3': '33.333333%',
        '2/3': '66.666667%',
        '1/4': '25%',
        '2/4': '50%',
        '3/4': '75%',
        '1/5': '20%',
        '2/5': '40%',
        '3/5': '60%',
        '4/5': '80%',
        '1/6': '16.666667%',
        '2/6': '33.333333%',
        '3/6': '50%',
        '4/6': '66.666667%',
        '5/6': '83.333333%',
        '1/12': '8.333333%',
        '2/12': '16.666667%',
        '3/12': '25%',
        '4/12': '33.333333%',
        '5/12': '41.666667%',
        '6/12': '50%',
        '7/12': '58.333333%',
        '8/12': '66.666667%',
        '9/12': '75%',
        '10/12': '83.333333%',
        '11/12': '91.666667%',
        full: '100%',
        '2full': '200%',
        screen: '100vw',
      },
    },
  },
  plugins: [
    animate,
    typography,
    forms,
    aspectRatio,
    {
      config: colors.plugin.config ?? {},
      handler: colors.plugin.handler,
    },
    {
      config: containerQueries.config ?? {},
      handler: containerQueries.handler,
    },
  ],
}
