/* eslint-disable @typescript-eslint/no-unsafe-call */
/* eslint-disable @typescript-eslint/no-unsafe-assignment */
/* eslint-disable @typescript-eslint/no-explicit-any */

import type { Config } from 'tailwindcss'

import aspectRatio from '@tailwindcss/aspect-ratio'
import containerQueries from '@tailwindcss/container-queries'
import forms from '@tailwindcss/forms'
import typography from '@tailwindcss/typography'
import animate from 'tailwindcss-animate'
import plugin from 'tailwindcss/plugin'
import { createPlugin } from 'windy-radix-palette'
import windyTypography from 'windy-radix-typography'

const colors = createPlugin()

export const prodktTailwindPreset: Config = {
  content: ['./src/**/*.{js,jsx,ts,tsx,mdx}'],
  presets: [windyTypography],
  theme: {
    extend: {
      backgroundImage: {
        'radial-gradient-1':
          'radial-gradient(87.07% 87.07% at 52.38% 100%, var(--grayA1) 0%, var(--grayA6) 100%)',
        'radial-gradient-2':
          'radial-gradient(100.44% 141.42% at 0% 0%, var(--grayA1) 0%, var(--grayA6) 100%);',
        'radial-gradient': 'radial-gradient(var(--tw-gradient-stops));',
        'conic-gradient':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
      colors: {
        amber: {
          1: 'var(--amber1)',
          2: 'var(--amber2)',
          3: 'var(--amber3)',
          4: 'var(--amber4)',
          5: 'var(--amber5)',
          6: 'var(--amber6)',
          7: 'var(--amber7)',
          8: 'var(--amber8)',
          9: 'var(--amber9)',
          10: 'var(--amber10)',
          11: 'var(--amber11)',
          12: 'var(--amber12)',
          a1: 'var(--amberA1)',
          a2: 'var(--amberA2)',
          a3: 'var(--amberA3)',
          a4: 'var(--amberA4)',
          a5: 'var(--amberA5)',
          a6: 'var(--amberA6)',
          a7: 'var(--amberA7)',
          a8: 'var(--amberA8)',
          a9: 'var(--amberA9)',
          a10: 'var(--amberA10)',
          a11: 'var(--amberA11)',
          a12: 'var(--amberA12)',
        },
        blue: {
          1: 'var(--blue1)',
          2: 'var(--blue2)',
          3: 'var(--blue3)',
          4: 'var(--blue4)',
          5: 'var(--blue5)',
          6: 'var(--blue6)',
          7: 'var(--blue7)',
          8: 'var(--blue8)',
          9: 'var(--blue9)',
          10: 'var(--blue10)',
          11: 'var(--blue11)',
          12: 'var(--blue12)',
          a1: 'var(--blueA1)',
          a2: 'var(--blueA2)',
          a3: 'var(--blueA3)',
          a4: 'var(--blueA4)',
          a5: 'var(--blueA5)',
          a6: 'var(--blueA6)',
          a7: 'var(--blueA7)',
          a8: 'var(--blueA8)',
          a9: 'var(--blueA9)',
          a10: 'var(--blueA10)',
          a11: 'var(--blueA11)',
          a12: 'var(--blueA12)',
        },
        bronze: {
          1: 'var(--bronze1)',
          2: 'var(--bronze2)',
          3: 'var(--bronze3)',
          4: 'var(--bronze4)',
          5: 'var(--bronze5)',
          6: 'var(--bronze6)',
          7: 'var(--bronze7)',
          8: 'var(--bronze8)',
          9: 'var(--bronze9)',
          10: 'var(--bronze10)',
          11: 'var(--bronze11)',
          12: 'var(--bronze12)',
          a1: 'var(--bronzeA1)',
          a2: 'var(--bronzeA2)',
          a3: 'var(--bronzeA3)',
          a4: 'var(--bronzeA4)',
          a5: 'var(--bronzeA5)',
          a6: 'var(--bronzeA6)',
          a7: 'var(--bronzeA7)',
          a8: 'var(--bronzeA8)',
          a9: 'var(--bronzeA9)',
          a10: 'var(--bronzeA10)',
          a11: 'var(--bronzeA11)',
          a12: 'var(--bronzeA12)',
        },
        brown: {
          1: 'var(--brown1)',
          2: 'var(--brown2)',
          3: 'var(--brown3)',
          4: 'var(--brown4)',
          5: 'var(--brown5)',
          6: 'var(--brown6)',
          7: 'var(--brown7)',
          8: 'var(--brown8)',
          9: 'var(--brown9)',
          10: 'var(--brown10)',
          11: 'var(--brown11)',
          12: 'var(--brown12)',
          a1: 'var(--brownA1)',
          a2: 'var(--brownA2)',
          a3: 'var(--brownA3)',
          a4: 'var(--brownA4)',
          a5: 'var(--brownA5)',
          a6: 'var(--brownA6)',
          a7: 'var(--brownA7)',
          a8: 'var(--brownA8)',
          a9: 'var(--brownA9)',
          a10: 'var(--brownA10)',
          a11: 'var(--brownA11)',
          a12: 'var(--brownA12)',
        },
        crimson: {
          1: 'var(--crimson1)',
          2: 'var(--crimson2)',
          3: 'var(--crimson3)',
          4: 'var(--crimson4)',
          5: 'var(--crimson5)',
          6: 'var(--crimson6)',
          7: 'var(--crimson7)',
          8: 'var(--crimson8)',
          9: 'var(--crimson9)',
          10: 'var(--crimson10)',
          11: 'var(--crimson11)',
          12: 'var(--crimson12)',
          a1: 'var(--crimsonA1)',
          a2: 'var(--crimsonA2)',
          a3: 'var(--crimsonA3)',
          a4: 'var(--crimsonA4)',
          a5: 'var(--crimsonA5)',
          a6: 'var(--crimsonA6)',
          a7: 'var(--crimsonA7)',
          a8: 'var(--crimsonA8)',
          a9: 'var(--crimsonA9)',
          a10: 'var(--crimsonA10)',
          a11: 'var(--crimsonA11)',
          a12: 'var(--crimsonA12)',
        },
        cyan: {
          1: 'var(--cyan1)',
          2: 'var(--cyan2)',
          3: 'var(--cyan3)',
          4: 'var(--cyan4)',
          5: 'var(--cyan5)',
          6: 'var(--cyan6)',
          7: 'var(--cyan7)',
          8: 'var(--cyan8)',
          9: 'var(--cyan9)',
          10: 'var(--cyan10)',
          11: 'var(--cyan11)',
          12: 'var(--cyan12)',
          a1: 'var(--cyanA1)',
          a2: 'var(--cyanA2)',
          a3: 'var(--cyanA3)',
          a4: 'var(--cyanA4)',
          a5: 'var(--cyanA5)',
          a6: 'var(--cyanA6)',
          a7: 'var(--cyanA7)',
          a8: 'var(--cyanA8)',
          a9: 'var(--cyanA9)',
          a10: 'var(--cyanA10)',
          a11: 'var(--cyanA11)',
          a12: 'var(--cyanA12)',
        },
        gold: {
          1: 'var(--gold1)',
          2: 'var(--gold2)',
          3: 'var(--gold3)',
          4: 'var(--gold4)',
          5: 'var(--gold5)',
          6: 'var(--gold6)',
          7: 'var(--gold7)',
          8: 'var(--gold8)',
          9: 'var(--gold9)',
          10: 'var(--gold10)',
          11: 'var(--gold11)',
          12: 'var(--gold12)',
          a1: 'var(--goldA1)',
          a2: 'var(--goldA2)',
          a3: 'var(--goldA3)',
          a4: 'var(--goldA4)',
          a5: 'var(--goldA5)',
          a6: 'var(--goldA6)',
          a7: 'var(--goldA7)',
          a8: 'var(--goldA8)',
          a9: 'var(--goldA9)',
          a10: 'var(--goldA10)',
          a11: 'var(--goldA11)',
          a12: 'var(--goldA12)',
        },
        grass: {
          1: 'var(--grass1)',
          2: 'var(--grass2)',
          3: 'var(--grass3)',
          4: 'var(--grass4)',
          5: 'var(--grass5)',
          6: 'var(--grass6)',
          7: 'var(--grass7)',
          8: 'var(--grass8)',
          9: 'var(--grass9)',
          10: 'var(--grass10)',
          11: 'var(--grass11)',
          12: 'var(--grass12)',
          a1: 'var(--grassA1)',
          a2: 'var(--grassA2)',
          a3: 'var(--grassA3)',
          a4: 'var(--grassA4)',
          a5: 'var(--grassA5)',
          a6: 'var(--grassA6)',
          a7: 'var(--grassA7)',
          a8: 'var(--grassA8)',
          a9: 'var(--grassA9)',
          a10: 'var(--grassA10)',
          a11: 'var(--grassA11)',
          a12: 'var(--grassA12)',
        },
        green: {
          1: 'var(--green1)',
          2: 'var(--green2)',
          3: 'var(--green3)',
          4: 'var(--green4)',
          5: 'var(--green5)',
          6: 'var(--green6)',
          7: 'var(--green7)',
          8: 'var(--green8)',
          9: 'var(--green9)',
          10: 'var(--green10)',
          11: 'var(--green11)',
          12: 'var(--green12)',
          a1: 'var(--greenA1)',
          a2: 'var(--greenA2)',
          a3: 'var(--greenA3)',
          a4: 'var(--greenA4)',
          a5: 'var(--greenA5)',
          a6: 'var(--greenA6)',
          a7: 'var(--greenA7)',
          a8: 'var(--greenA8)',
          a9: 'var(--greenA9)',
          a10: 'var(--greenA10)',
          a11: 'var(--greenA11)',
          a12: 'var(--greenA12)',
        },
        indigo: {
          1: 'var(--indigo1)',
          2: 'var(--indigo2)',
          3: 'var(--indigo3)',
          4: 'var(--indigo4)',
          5: 'var(--indigo5)',
          6: 'var(--indigo6)',
          7: 'var(--indigo7)',
          8: 'var(--indigo8)',
          9: 'var(--indigo9)',
          10: 'var(--indigo10)',
          11: 'var(--indigo11)',
          12: 'var(--indigo12)',
          a1: 'var(--indigoA1)',
          a2: 'var(--indigoA2)',
          a3: 'var(--indigoA3)',
          a4: 'var(--indigoA4)',
          a5: 'var(--indigoA5)',
          a6: 'var(--indigoA6)',
          a7: 'var(--indigoA7)',
          a8: 'var(--indigoA8)',
          a9: 'var(--indigoA9)',
          a10: 'var(--indigoA10)',
          a11: 'var(--indigoA11)',
          a12: 'var(--indigoA12)',
        },
        iris: {
          1: 'var(--iris1)',
          2: 'var(--iris2)',
          3: 'var(--iris3)',
          4: 'var(--iris4)',
          5: 'var(--iris5)',
          6: 'var(--iris6)',
          7: 'var(--iris7)',
          8: 'var(--iris8)',
          9: 'var(--iris9)',
          10: 'var(--iris10)',
          11: 'var(--iris11)',
          12: 'var(--iris12)',
          a1: 'var(--irisA1)',
          a2: 'var(--irisA2)',
          a3: 'var(--irisA3)',
          a4: 'var(--irisA4)',
          a5: 'var(--irisA5)',
          a6: 'var(--irisA6)',
          a7: 'var(--irisA7)',
          a8: 'var(--irisA8)',
          a9: 'var(--irisA9)',
          a10: 'var(--irisA10)',
          a11: 'var(--irisA11)',
          a12: 'var(--irisA12)',
        },
        jade: {
          1: 'var(--jade1)',
          2: 'var(--jade2)',
          3: 'var(--jade3)',
          4: 'var(--jade4)',
          5: 'var(--jade5)',
          6: 'var(--jade6)',
          7: 'var(--jade7)',
          8: 'var(--jade8)',
          9: 'var(--jade9)',
          10: 'var(--jade10)',
          11: 'var(--jade11)',
          12: 'var(--jade12)',
          a1: 'var(--jadeA1)',
          a2: 'var(--jadeA2)',
          a3: 'var(--jadeA3)',
          a4: 'var(--jadeA4)',
          a5: 'var(--jadeA5)',
          a6: 'var(--jadeA6)',
          a7: 'var(--jadeA7)',
          a8: 'var(--jadeA8)',
          a9: 'var(--jadeA9)',
          a10: 'var(--jadeA10)',
          a11: 'var(--jadeA11)',
          a12: 'var(--jadeA12)',
        },
        lime: {
          1: 'var(--lime1)',
          2: 'var(--lime2)',
          3: 'var(--lime3)',
          4: 'var(--lime4)',
          5: 'var(--lime5)',
          6: 'var(--lime6)',
          7: 'var(--lime7)',
          8: 'var(--lime8)',
          9: 'var(--lime9)',
          10: 'var(--lime10)',
          11: 'var(--lime11)',
          12: 'var(--lime12)',
          a1: 'var(--limeA1)',
          a2: 'var(--limeA2)',
          a3: 'var(--limeA3)',
          a4: 'var(--limeA4)',
          a5: 'var(--limeA5)',
          a6: 'var(--limeA6)',
          a7: 'var(--limeA7)',
          a8: 'var(--limeA8)',
          a9: 'var(--limeA9)',
          a10: 'var(--limeA10)',
          a11: 'var(--limeA11)',
          a12: 'var(--limeA12)',
        },
        mauve: {
          1: 'var(--mauve1)',
          2: 'var(--mauve2)',
          3: 'var(--mauve3)',
          4: 'var(--mauve4)',
          5: 'var(--mauve5)',
          6: 'var(--mauve6)',
          7: 'var(--mauve7)',
          8: 'var(--mauve8)',
          9: 'var(--mauve9)',
          10: 'var(--mauve10)',
          11: 'var(--mauve11)',
          12: 'var(--mauve12)',
          a1: 'var(--mauveA1)',
          a2: 'var(--mauveA2)',
          a3: 'var(--mauveA3)',
          a4: 'var(--mauveA4)',
          a5: 'var(--mauveA5)',
          a6: 'var(--mauveA6)',
          a7: 'var(--mauveA7)',
          a8: 'var(--mauveA8)',
          a9: 'var(--mauveA9)',
          a10: 'var(--mauveA10)',
          a11: 'var(--mauveA11)',
          a12: 'var(--mauveA12)',
        },
        slate: {
          1: 'var(--slate1)',
          2: 'var(--slate2)',
          3: 'var(--slate3)',
          4: 'var(--slate4)',
          5: 'var(--slate5)',
          6: 'var(--slate6)',
          7: 'var(--slate7)',
          8: 'var(--slate8)',
          9: 'var(--slate9)',
          10: 'var(--slate10)',
          11: 'var(--slate11)',
          12: 'var(--slate12)',
          a1: 'var(--slateA1)',
          a2: 'var(--slateA2)',
          a3: 'var(--slateA3)',
          a4: 'var(--slateA4)',
          a5: 'var(--slateA5)',
          a6: 'var(--slateA6)',
          a7: 'var(--slateA7)',
          a8: 'var(--slateA8)',
          a9: 'var(--slateA9)',
          a10: 'var(--slateA10)',
          a11: 'var(--slateA11)',
          a12: 'var(--slateA12)',
        },
        background: 'var(--gray1)',
        foreground: 'var(--gray12)',

        muted: {
          DEFAULT: 'var(--gray4)',
          foreground: 'var(--gray11)',
        },

        card: {
          DEFAULT: 'hsl(var(--gray2))',
          foreground: 'var(--gray11)',
        },

        popover: {
          // DEFAULT: 'hsl(var(--gray9))',
          DEFAULT: 'var(--gray3)',
          foreground: 'var(--gray11)',
        },

        input: 'var(--gray4)',

        accent: {
          DEFAULT: 'var(--accent11)',
          hover: 'var(--accent12)',
          selected: 'var(--accent12)',
          foreground: 'var(--accent2)',
          1: 'var(--accent1)',
          2: 'var(--accent2)',
          3: 'var(--accent3)',
          4: 'var(--accent4)',
          5: 'var(--accent5)',
          6: 'var(--accent6)',
          7: 'var(--accent7)',
          8: 'var(--accent8)',
          9: 'var(--accent9)',
          10: 'var(--accent10)',
          11: 'var(--accent11)',
          12: 'var(--accent12)',
        },

        gray: {
          DEFAULT: 'var(--gray11)',
          hover: 'var(--gray12)',
          selected: 'var(--gray12)',
          foreground: 'var(--gray2)',
          1: 'var(--gray1)',
          2: 'var(--gray2)',
          3: 'var(--gray3)',
          4: 'var(--gray4)',
          5: 'var(--gray5)',
          6: 'var(--gray6)',
          7: 'var(--gray7)',
          8: 'var(--gray8)',
          9: 'var(--gray9)',
          10: 'var(--gray10)',
          11: 'var(--gray11)',
          12: 'var(--gray12)',
        },

        primary: {
          DEFAULT: 'var(--violet9)',
          foreground: 'var(--violet1)',
          1: 'var(--violet1)',
          2: 'var(--violet2)',
          3: 'var(--violet3)',
          4: 'var(--violet4)',
          5: 'var(--violet5)',
          6: 'var(--violet6)',
          7: 'var(--violet7)',
          8: 'var(--violet8)',
          9: 'var(--violet9)',
          10: 'var(--violet10)',
          11: 'var(--violet11)',
          12: 'var(--violet12)',
        },

        ghost: {
          DEFAULT: 'var(--ghost-a2)',
          a1: 'var(--ghost-a1)',
          a2: 'var(--ghost-a2)',
          a3: 'var(--ghost-a3)',
          a4: 'var(--ghost-a4)',
          a5: 'var(--ghost-a5)',
          a6: 'var(--ghost-a6)',
          a7: 'var(--ghost-a7)',
          a8: 'var(--ghost-a8)',
          a9: 'var(--ghost-a9)',
          a10: 'var(--ghost-a10)',
          a11: 'var(--ghost-a11)',
          a12: 'var(--ghost-a12)',
          aa1: 'var(--ghost-aa1)',
          aa2: 'var(--ghost-aa2)',
          aa3: 'var(--ghost-aa3)',
          aa4: 'var(--ghost-aa4)',
          aa5: 'var(--ghost-aa5)',
          aa6: 'var(--ghost-aa6)',
          aa7: 'var(--ghost-aa7)',
          aa8: 'var(--ghost-aa8)',
          aa9: 'var(--ghost-aa9)',
          aa10: 'var(--ghost-aa10)',
          aa11: 'var(--ghost-aa11)',
          aa12: 'var(--ghost-aa12)',
          1: 'var(--ghost-1)',
          2: 'var(--ghost-2)',
          3: 'var(--ghost-3)',
          4: 'var(--ghost-4)',
          5: 'var(--ghost-5)',
          6: 'var(--ghost-6)',
          7: 'var(--ghost-7)',
          8: 'var(--ghost-8)',
          9: 'var(--ghost-9)',
          10: 'var(--ghost-10)',
          11: 'var(--ghost-11)',
          12: 'var(--ghost-12)',
        },

        secondary: {
          DEFAULT: 'var(--blue10)',
          foreground: 'var(--blue1)',
          1: 'var(--blue1)',
          2: 'var(--blue2)',
          3: 'var(--blue3)',
          4: 'var(--blue4)',
          5: 'var(--blue5)',
          6: 'var(--blue6)',
          7: 'var(--blue7)',
          8: 'var(--blue8)',
          9: 'var(--blue9)',
          10: 'var(--blue10)',
          11: 'var(--blue11)',
          12: 'var(--blue12)',
        },

        destructive: {
          DEFAULT: 'var(--red9)',
          foreground: 'var(--red1)',
          1: 'var(--red1)',
          2: 'var(--red2)',
          3: 'var(--red3)',
          4: 'var(--red4)',
          5: 'var(--red5)',
          6: 'var(--red6)',
          7: 'var(--red7)',
          8: 'var(--red8)',
          9: 'var(--red9)',
          10: 'var(--red10)',
          11: 'var(--red11)',
          12: 'var(--red12)',
        },

        border: 'var(--grayA4)',
        ring: 'var(--grayA4)',
      },
      borderRadius: {
        radius: '0.5rem',
      },
      fontFamily: {
        sans: ['var(--font-labil-grotesk)'],
        mono: ['var(--font-ibm-plex-mono)'],
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        'caret-blink': {
          '0%,70%,100%': { opacity: '1' },
          '20%,50%': { opacity: '0' },
        },
        marquee: {
          from: { transform: 'translateX(0)' },
          to: { transform: 'translateX(calc(-100% - var(--gap)))' },
        },
        'marquee-vertical': {
          from: { transform: 'translateY(0)' },
          to: { transform: 'translateY(calc(-100% - var(--gap)))' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'caret-blink': 'caret-blink 1.25s ease-out infinite',
        spinSlow1x: 'spin 20.25s linear infinite',
        spinSlow2x: 'spin 22.25s linear infinite',
        spinSlow3x: 'spin 24.25s linear infinite',
        spinSlow4x: 'spin 26.25s linear infinite',
        marquee: 'marquee var(--duration) linear infinite',
        'marquee-vertical': 'marquee-vertical var(--duration) linear infinite',
        'border-beam': 'border-beam calc(var(--duration)*1s) infinite linear',
      },
      transitionDelay: {
        0: '0s',
        75: '75ms',
        100: '100ms',
        150: '150ms',
        200: '200ms',
        300: '300ms',
        500: '500ms',
        700: '700ms',
        1000: '1000ms',
      },
      transitionDuration: {
        DEFAULT: '150ms',
        0: '0s',
        75: '75ms',
        100: '100ms',
        150: '150ms',
        200: '200ms',
        300: '300ms',
        500: '500ms',
        700: '700ms',
        1000: '1000ms',
      },
      transitionProperty: {
        none: 'none',
        all: 'all',
        DEFAULT:
          'color, background-color, border-color, text-decoration-color, fill, stroke, opacity, box-shadow, transform, filter, backdrop-filter',
        colors:
          'color, background-color, border-color, text-decoration-color, fill, stroke',
        opacity: 'opacity',
        shadow: 'box-shadow',
        transform: 'transform',
      },
      transitionTimingFunction: {
        DEFAULT: 'cubic-bezier(0.4, 0, 0.2, 1)',
        linear: 'linear',
        in: 'cubic-bezier(0.4, 0, 1, 1)',
        out: 'cubic-bezier(0, 0, 0.2, 1)',
        'in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      width: {
        auto: 'auto',
        '1/2': '50%',
        '1/3': '33.333333%',
        '2/3': '66.666667%',
        '1/4': '25%',
        '2/4': '50%',
        '3/4': '75%',
        '1/5': '20%',
        '2/5': '40%',
        '3/5': '60%',
        '4/5': '80%',
        '1/6': '16.666667%',
        '2/6': '33.333333%',
        '3/6': '50%',
        '4/6': '66.666667%',
        '5/6': '83.333333%',
        '1/12': '8.333333%',
        '2/12': '16.666667%',
        '3/12': '25%',
        '4/12': '33.333333%',
        '5/12': '41.666667%',
        '6/12': '50%',
        '7/12': '58.333333%',
        '8/12': '66.666667%',
        '9/12': '75%',
        '10/12': '83.333333%',
        '11/12': '91.666667%',
        full: '100%',
        '2full': '200%',
        screen: '100vw',
      },
    },
  },
  plugins: [
    // biome-ignore lint/suspicious/noExplicitAny: <explanation>
    plugin(({ matchUtilities, theme }: any) => {
      matchUtilities(
        {
          // biome-ignore lint/suspicious/noExplicitAny: <explanation>
          'translate-z': (value: any) => ({
            '--tw-translate-z': value,
            transform:
              ' translate3d(var(--tw-translate-x), var(--tw-translate-y), var(--tw-translate-z)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))',
          }), // this is actual CSS
          // biome-ignore lint/suspicious/noExplicitAny: <explanation>
          'text-shadow': (value: any) => ({
            textShadow: value,
          }),
        },
        { values: theme('textShadow') },
        { values: theme('translate'), supportsNegativeValues: true },
      )
    }),
    // biome-ignore lint/suspicious/noExplicitAny: <explanation>
    plugin(({ addUtilities }: any) => {
      const newUtilities = {
        '.text-shadow-glow': {
          textShadow:
            '0 0 5px rgba(0, 255, 0, 0.7), 0 0 10px rgba(0, 255, 0, 0.5)',
        },
      }
      addUtilities(newUtilities)
    }),
    animate,
    typography,
    forms,
    aspectRatio,
    {
      config: colors.plugin.config ?? {},
      handler: colors.plugin.handler,
    },
    {
      config: containerQueries.config ?? {},
      handler: containerQueries.handler,
    },
  ],
}
